### PR TITLE
Query base path should be used to configure correct path in ingress

### PR DESCRIPTION
**Pull request by objectiser**
If the query UI base path is defined, then the Ingress needs to also use that path (based on a recent PR in Istio helm chart https://github.com/istio/istio/pull/9588).

Need to consider whether this should also be applied to Route?

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/108)

**Comment by objectiser** [comment]
The following image shows accessing the Jaeger UI through port forwarding using the updated all-in-one-with-options.yaml. When accessing through the ingress, the UI URL is the same as before (i.e. just `/search`).

jaeger-base-path

**Comment by objectiser** [comment]
@jpkrohling I've included an initial e2e test but it is currently only checking that the ingress uses the same URI (i.e. the base path is not present).

To check the base path, I will need to obtain an address/port that is normally exposed by running a port-forward. Any idea how would do this? If not I will experiment - its just it takes a while to run the e2e tests :)

BTW - might be better if the e2e tests output more than a single line - I only got:
```
Running end-to-end tests...
ok  	github.com/jaegertracing/jaeger-operator/test/e2e	262.266s
```
Is there anyway to get it to output per individual test?

**Comment by jpkrohling** [comment]
> To check the base path, I will need to obtain an address/port that is normally exposed by running a port-forward. Any idea how would do this? If not I will experiment

I think the code you have in the PR should already be very close, you just need to call it from `JaegerAllInOne`. Or you can create a new source file + new test to host this new scenario and then add it to `jaeger_test.go`.

> its just it takes a while to run the e2e tests :)

The tests are regular Go tests, so, you shouldn't be hard to add a new Makefile target that runs a specific test like `go test -run TestName`. Or you can just comment out the other tests in `jaeger_tests.go`, which is what lazy-me does.

> BTW - might be better if the e2e tests output more than a single line - I only got:

Agree, but that's standard Go and Operator SDK :/ Not sure if we can control that, or how.

**Comment by objectiser** [comment]
@jpkrohling Ok calling the test - however the problem is that aswell as testing the ingress, I need to test a port directly on the pod, against a URL "/jaeger/search".

**Comment by objectiser** [comment]
@jpkrohling done

**Pull request merged**
