### PR TITLE
Added publishing of major.minor image for the operator

### LINKED ISSUE #187: Jaeger operator docker image should be tagged major.minor and possibly also major
Currently requires major.minor.patch to be specified so gets specific version.

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes #187 
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/274)

**Comment by objectiser** [comment]
Is it worth doing major version aswell?

**Comment by jpkrohling** [comment]
We could, although I don't remember seeing it used in practice.

**Comment by jpkrohling** [comment]
I'll merge this without tagging only the major part. If we get a request for that, we could implement based on the logic from this PR.

**Pull request merged**
