### PR TITLE
Enable agent readiness probe

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/297)

**Comment by objectiser** [comment]
@pavolloffay travis failed - I had same issue and had to restart the build - looks like a spurious problem finding golint.

**Comment by pavolloffay** [comment]
I will have a look at it

**Comment by pavolloffay** [comment]
locally the installation worked well. I will restart it again

**Pull request merged**
