### PR TITLE
Agent service ports with correct protocol

### PR DESCRIPTION
**Pull request by dnovvak**
Fixes: #577

### CODE REVIEW

**Comment by jpkrohling** [comment]
@objectiser  I think the general recommendation is to use the downward API to get the node's IP and configure the client to go directly to the node, so, this service here shouldn't be used much (at all?). Do you remember if and where this service is used?

In any case, the PR looks correct in that it's setting the ports to their expected protocols.

**Comment by jpkrohling** [comment]
@dnovvak: the same question applies to you: what makes you use the service instead of the downward API to get the local node's IP?

**Comment by objectiser** [comment]
@jpkrohling no where as far as I know.

**Comment by jpkrohling** [comment]
@dnovvak could you please run `make format` and update this PR?

**Comment by dnovvak** [comment]
@jpkrohling Yes, just fixed formatting. It was not so easy on windows :) thanks for patience

>
> 
> @dnovvak: the same question applies to you: what makes you use the service instead of the downward API to get the local node's IP?

My use case is rather unusual and shouldn't be considered as important I think. I needed to expose agent outside k8s cluster (only for dev/test purpose, for a while). I tried to do this through nginx ingress ([details here](https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/)) but without success. After quick investigation I found that service for jaeger-agent did not expose UDP ports but all TCP. That's the story.

**Pull request merged**
