### PR TITLE
Fix: setting default Istio annotation in Pod instead of Deployment

### PR DESCRIPTION
**Pull request by cnvergence**
Properly add istio annotation to Pod instead of Deployment.
Fixes `istioctl analyze` warning 
```bash
Warning [IST0107] (Deployment kyma-system/tracing-jaeger) Misplaced annotation: sidecar.istio.io/inject can only be applied to Pod
```

## Which problem is this PR solving?
- 
Resolves:
- https://github.com/jaegertracing/jaeger-operator/issues/1330
- thanks to the issue reporter @xM8WVqaG

### CODE REVIEW

**Review by frzifus — APPROVED** [review]
makes sense to me. What do you think @rubenvp8510 ?

**Comment by cnvergence** [comment]
hey @frzifus, could you take a look again, please?
I have updated this PR, so I think it can solve the problem with `sidecar.istio.io` annotations
- https://github.com/jaegertracing/helm-charts/issues/355

**Review by frzifus — APPROVED** [review]

**Comment by rubenvp8510** [comment]
> makes sense to me. What do you think @rubenvp8510 ?

Yep, it makes sense to me.

**Comment by cnvergence** [comment]
@rubenvp8510 @frzifus I needed to update this branch, ptal
Thanks!

**Comment by frzifus** [comment]
sure

**Review by frzifus — APPROVED** [review]

**Review by rubenvp8510 — APPROVED** [review]

**Pull request merged**
