### PR TITLE
support volumes and volumeMounts

### PR DESCRIPTION
**Pull request by clyang82**
This PR is to fix the issue - https://github.com/jaegertracing/jaeger-operator/issues/76
This goal is to support add `volumes` and `volumeMounts` in kind `Jaeger`

Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by clyang82** [comment]
@jpkrohling Thanks for your comments. most of them were addressed today except for document update. I will update tomorrow.

**Comment by clyang82** [comment]
@jpkrohling Thanks for your time to review my PR. All your comments were addressed. I would like to open another PR for document update so that the PR is ready for merge if no further comments.

**Comment by jpkrohling** [comment]
Thanks for your contribution, @clyang82 !

**Comment by clyang82** [comment]
the review comments were fixed in https://github.com/jaegertracing/jaeger-operator/pull/98. Thanks for your help. @jpkrohling

**Pull request merged**
