### PR TITLE
feat: added pathType to ingress

### PR DESCRIPTION
**Pull request by giautm**
## Which problem is this PR solving?
- Resolve https://github.com/jaegertracing/jaeger-operator/issues/2065

## Short description of the changes
- Added `pathType` to `ingress`

### CODE REVIEW

**Comment by frzifus** [comment]
thats awesome, thanks @giautm. I will have a more detailed look later today.

**Comment by frzifus** [comment]
Seems some formating is wrong.
```
 Checking...
Go fmt, license check, or import ordering failures, run 'make format'
pkg/ingress/query_test.go
make: *** [Makefile:119: check] Error 1
```

**Comment by giautm** [comment]
Hello @frzifus , review again please?

**Review by frzifus — APPROVED** [review]
great work :)

**Comment by giautm** [comment]
Hello @frzifus, can you create another release for helm-chart, please?

**Pull request merged**
