### PR TITLE
Update the Operator SDK version

### PR DESCRIPTION
**Pull request by jpkrohling**
This PR changes the operator SDK version to use a fixed version, along with the necessary changes to get it working with this new version.

This is part of #66.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/69)

**Comment by jpkrohling** [comment]
@pavolloffay, would you like to review this one?

**Comment by jpkrohling** [comment]
Don't mind the changes inside `vendor`, it's sufficient if you take a look at the other changes :)

**Comment by pavolloffay** [comment]
it was a joke.. :)

**Pull request merged**
