### PR TITLE
Set non-root user group

### PR DESCRIPTION
**Pull request by UsaninMax**
Based on https://github.com/jaegertracing/jaeger-operator/issues/1336#issue-760280621

### CODE REVIEW

**Comment by jpkrohling** [comment]
Could you please work on the DCO check?

**Comment by jpkrohling** [comment]
https://github.com/jaegertracing/jaeger-operator/pull/1337/checks?check_run_id=1525256256

**Comment by UsaninMax** [comment]
@jpkrohling  Hi, I added Signed-off already but it's not working... what could be wrong with that ?

**Comment by jpkrohling** [comment]
There are three commits in the PR, the first one is missing the sign-off: 

image

You might want to squash all commits, and sign-off the resulting: `git rebase -i master` (select pick for the first, squash for the other two), then `git commit --amend --signoff` to make sure the single commit is signed-off. Finally, force-push it.

**Comment by UsaninMax** [comment]
> There are three commits in the PR, the first one is missing the sign-off:
> 
> image
> 
> You might want to squash all commits, and sign-off the resulting: `git rebase -i master` (select pick for the first, squash for the other two), then `git commit --amend --signoff` to make sure the single commit is signed-off. Finally, force-push it.

if they were already pushed to the master? and now I do not see any options to pick and squash...
image

**Comment by jpkrohling** [comment]
> if they were already pushed to the master?

You can try `upstream/master` then instead. But it's a good reason to use a feature branch: `git checkout -b pr1337` ;-)

**Comment by UsaninMax** [comment]
@jpkrohling I created new one, and DCO is ok 

https://github.com/jaegertracing/jaeger-operator/pull/1339

**Comment by jpkrohling** [comment]
Closing in favor of #1339

**Pull request closed without merging**
