### PR TITLE
Add image pull secrets

### PR DESCRIPTION
**Pull request by objectiser**
Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
Just wondering whether `JaegerDependenciesSpec`, `JaegerEsIndexCleanerSpec`, `JaegerEsRolloverSpec` and `JaegerCassandraCreateSchemaSpec` should also have `CommonSpec`? Currently these just use the `ImagePullSecrets` from the top level spec.

**Comment by pavolloffay** [comment]
> Just wondering whether JaegerDependenciesSpec, JaegerEsIndexCleanerSpec, JaegerEsRolloverSpec and JaegerCassandraCreateSchemaSpec should also have CommonSpec?

Probably yes, could we track it in a separate issue?


Regarding this PR, It looks good to me if this is the approach how people pull images from private repositories. I thought maybe there is a way to authenticate the docker client on the node which then would not require adding these settings for every container.

**Comment by objectiser** [comment]
> Probably yes, could we track it in a separate issue?

@pavolloffay Will create a separate issue for this.

> I thought maybe there is a way to authenticate the docker client on the node which then would not require adding these settings for every container.

Yes I believe that is true - although Istio (and probably others) still provide support for defining the secret on a component by component basis aswell - so I guess there are cases where this may be necessary.

**Comment by jpkrohling** [comment]
What's the status of this one?

**Comment by objectiser** [comment]
@jpkrohling unclear whether required, so we could either provide for completeness or wait for explicit request?

**Comment by jpkrohling** [comment]
I'm closing this one then. Once we have a request for it, it's probably easier to open a new PR than work on this one, given the amount of conflicts.

**Pull request closed without merging**
