### PR TITLE
Extended compatibility matrix

### PR DESCRIPTION
**Pull request by mooneeb**
## Which problem is this PR solving?
Resolves https://github.com/jaegertracing/jaeger-operator/issues/2506

## Description of the changes
This PR extends the compatibility matrix by adding the missing Jaeger Operator versions.

## How was this change tested?
Ran the command: `make lint test`

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by mooneeb** [comment]
I see that Jaeger Operator `v1.50` is present in the [documentation](https://www.jaegertracing.io/docs/1.50/) but I couldn't find the relevant tag in the codebase for it.

Inferring from the compatibility matrix of the versions, I added the compatibility for v1.50 base on the assumption that it would be compatible with the same Kubernetes, Strimzi Operator, and Cert-Manager as the versions above it.

Please let me know if that's alright?

**Review by frzifus — APPROVED** [review]

**Comment by frzifus** [comment]
Thanks for brining this up :)
Let me check ^^

**Comment by mooneeb** [comment]
> Thanks for brining this up :) Let me check ^^

Thank you!

I just realised I actually forgot to push the compatibility for v1.50. I'll do that once you give me the go ahead.

Another thing, shall I also update the text at the top of the Compatibility.md?

```diff
- The following table shows the compatibility of jaeger operator with different components, in this particular case we shows Kubernetes and Strimzi operator compatibility
+ The following table shows the compatibility of Jaeger Operator with three different components: Kubernetes, Strimzi Operator, and Cert-Manager.
```

**Comment by iblancasa** [comment]
> Another thing, shall I also update the text at the top of the Compatibility.md as follows (if you think this change is needed i.e.):

Yes, please!

**Review by iblancasa — APPROVED** [review]

**Comment by mooneeb** [comment]
@

> > Another thing, shall I also update the text at the top of the Compatibility.md as follows (if you think this change is needed i.e.):
> 
> Yes, please!

Updated :)

The only thing left is the compatibility for `v1.50` and whether I should add that to the table. Need your guidance there.

**Comment by iblancasa** [comment]
Yes. Add it. That data is correct.

**Pull request merged**
