### PR TITLE
Convert storage type to typed string

### PR DESCRIPTION
**Pull request by SezalAgrawal**
The JaegerStorageSpec currently has the storage type as a string. It is changed to a typed string. This PR also includes changes in storage type in all the required files.

Resolves: #111
Signed-off-by: Sezal Agrawal <sezalagrawal@gmail.com>

### CODE REVIEW

**Comment by SezalAgrawal** [comment]
@jpkrohling I ran `make generate` and have committed the new zz_generated.openapi.go. The build is still failing with error message `Build failed: a model has been changed but the generated resources aren't up to date. Run 'make generate' and update your PR.`

**Comment by jpkrohling** [comment]
This looks like a path issue: take a look at the changes for the generated `openapi`, `GetOpenAPIDefinitions` function. Do you have a GOPATH set?

**Review by kevinearls — APPROVED** [review]
LGTM

**Review by jpkrohling — APPROVED** [review]
Marking this as approved based on @kevinearls's review.

**Comment by jpkrohling** [comment]
Thank you for your contribution!

**Pull request merged**
