### PR TITLE
Add scheduler.alpha.kubernetes.io/critical-pod annotation to all pods

### PR DESCRIPTION
**Pull request by objectiser**
Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
Do you have some resources about this annotation? The only page I could find in the docs is the following:

https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-add-on-as-critical

Two things caught my attention:

1. Critical pods are the ones that might cause the *cluster* to stop operating correctly, which I don't think is our case;
1. This annotation will be removed in 1.13/1.14. Is there a more long-term solution we should be using instead?

**Comment by objectiser** [comment]
@jpkrohling This was added based on the comment https://github.com/istio/istio/pull/9508#issuecomment-435560389. Regarding a long term solution, we could follow Istio's lead and update the approach in the future.

We could also make it optional if would prefer?

**Comment by jpkrohling** [comment]
I have nothing against it, but I have to admit that I don't fully understand the implications this would have for applications in highly constrained clusters. For instance, between running an application pod and a Jaeger pod, I would say that the application pod has precedence, while this annotation would tell the Kubernetes that Jaeger pods are more critical.

**Comment by objectiser** [comment]
@jpkrohling Understand your concern - so either we could provide a parameter to configure, or just a generic "annotations" section that would be applied to all pods?

My preference would probably be a specific parameter (default true so only actually used in cases where may cause problems) - to avoid issues of knowing what pods are actually deployed and whether the annotation(s) should be applied to all. Thoughts?

**Comment by jpkrohling** [comment]
> or just a generic "annotations" section that would be applied to all pods

This would scale better, IMO.

I'm OK in merging this one for now, if you open an issue with the request.

**Pull request closed without merging**
