### PR TITLE
Restore this test, it works with version 4.1.2 of the elasticsearch o…

### PR DESCRIPTION
**Pull request by kevinearls**
…perator

Signed-off-by: Kevin Earls <kearls@redhat.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling Should we change the README (and possibly `deploy-es-operator`) to identify the dependence of es-operator 4.1?

**Comment by kevinearls** [comment]
@objectiser @jpkrohling If this looks ok can one of you merge it?

**Comment by objectiser** [comment]
@jpkrohling Do we need to add something to the readme to indicate "works with 4.1.x of the es operator"?

**Comment by objectiser** [comment]
@kevinearls @jpkrohling I'll merge this for now, but we need to determine how best to handle the differences that will occur if instructions and scripts (e.g.`make deploy-es-operator`) continue to refer to es-operator master.

**Comment by jpkrohling** [comment]
> Should we change the README (and possibly deploy-es-operator) to identify the dependence of es-operator 4.1?

I guess we'll soon need a compatibility matrix: OpenShift/Kubernetes/ES Operator x Jaeger Operator.

**Pull request merged**
