### PR TITLE
add kafkaSecretName for collector and ingester

### LINKED ISSUE #1422: Support passing Kafka username/password as K8S secrets
**Problem to Solve** 

I am using the existing Kafka for the `streaming` strategy. Looks like there's no option to pass the Kafka username/password as K8S secret to jaeger-collector and ingester. It would be good to support it.

**Proposed Solution** 
Passing the Kafka username/password as a K8S secret.

**More info**
This is my current config in Jsonnet. It passed the username/password as the container args which lacks protection.

```jsonnet
    topic: "jaeger-spans",
    brokers: "cell-1.streaming.us-phoenix-1.oci.oraclecloud.com:9092",
    authentication: "plaintext",
    plaintext: {
      username: $.streaming_username,
      password: $.streaming_password,
    },
    "protocol-version": "2.1.1",
    tls: {
      enabled: true,
    },
```

Before trying Jaeger Operator, I used to handle them as env vars.
```yaml
        env:
          - name: KAFKA_CONSUMER_PLAINTEXT_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: jaegerkafkaauth
          - name: KAFKA_CONSUMER_PLAINTEXT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: jaegerkafkaauth
```

### PR DESCRIPTION
**Pull request by luohua13**
## Which problem is this PR solving?
 Resolves #1422 

## Short description of the changes
Add kafkaSecretName for collctor and ingester

### CODE REVIEW

**Comment by rubenvp8510** [comment]
@luohua13 CI is complaining about format issue, Could you fix it? other than that the PR LGTM.

**Comment by luohua13** [comment]
> 



> @luohua13 CI is complaining about format issue, Could you fix it? other than that the PR LGTM.

ok, I will fix it.

**Comment by rubenvp8510** [comment]
> > 
> 
> > @luohua13 CI is complaining about format issue, Could you fix it? other than that the PR LGTM.
> 
> ok, I will fix it.

Thank you! 🎉

**Review by frzifus — APPROVED** [review]

**Comment by luohua13** [comment]
@rubenvp8510 Can you review it again? And then merge it?

**Review by rubenvp8510 — APPROVED** [review]

**Pull request merged**
