### PR TITLE
[REQUIRED 1.15.0] revert TLS workaround when 1.15.0 images are available

### PR DESCRIPTION
**Pull request by kevinearls**
Signed-off-by: Kevin Earls <kearls@redhat.com>

Merge this once 1.15.0 images are available

### CODE REVIEW

**Comment by jpkrohling** [comment]
This should probably be out of draft now, right ?

**Comment by kevinearls** [comment]
@jpkrohling I think so, will take a look next week.

**Comment by jpkrohling** [comment]
@kevinearls is this still relevant?

**Comment by kevinearls** [comment]
@jpkrohling I'll check it now

**Pull request merged**
