### PR TITLE
add labels to cronjob pod template

### LINKED ISSUE #697: No identifying labels on ES Index Cleaner pod
I am trying to setup network policies for my 'monitoring' namespace. This includes restricting access to ElasticSearch to Jaeger. 
I can easily create a policy for Jaeger itself by matching on app=jaeger annotation, but unfortunately pods created by ES cleaner cron job have no identifying annotations.
Please modify cronjob template to add annotations that can be used to identify cleaner pod.

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

fixes #697

### CODE REVIEW

**Comment by yeya24** [comment]
> Looks good! The only thing missing is a test, to make sure the expected labels can be found on both expected places.

Sure, I will add it ASAP

**Comment by yeya24** [comment]
> Looks good! The only thing missing is a test, to make sure the expected labels can be found on both expected places.

@jpkrohling Could you please check if this is OK? Thank you very much.

**Comment by yeya24** [comment]
Seems the install-docker script has some problems...

**Comment by jpkrohling** [comment]
image

I started the failed checks again. Once it passes, I'll merge it.

**Comment by jpkrohling** [comment]
@yeya24 thanks for your PR!

**Pull request merged**
