### PR TITLE
Add commonSpec to other jobs (es-index-cleaner, es-rollover, cassandr…

### PR DESCRIPTION
**Pull request by objectiser**
…a-create-schema)

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling Seems like a problem with the github actions, created a fresh PR (not rebased) - failed on streaming test first time around (with 2 other e2e tests cancelled) but then when restarted it complains on the checkout. Any idea how best to proceed?

**Comment by jpkrohling** [comment]
Are you or @kevinearls able to run the e2e tests for Cassandra locally? If they succeed, I'm comfortable in merging this, as that's the only one that hasn't succeeded between all the runs.

**Comment by kevinearls** [comment]
@jpkrohling The cassandra tests work locally for me.  FYI I have had problems getting some tests to run here.  For example, the streaming tests have failed here repeatedly https://github.com/jaegertracing/jaeger-operator/pull/636   I cannot, however, reproduce this failure on my laptop, either using minikube or OCP 4.1

**Comment by objectiser** [comment]
@kevinearls Thanks - I've just done a minor refactor so will see if tests are working better today. Could you try running all of the e2e tests locally based on this updated PR? When I tried the cassandra test it timed out - but will try again.

**Comment by kevinearls** [comment]
@objectiser Sure, I'll try it shortly.

**Comment by kevinearls** [comment]
@jpkrohling @objectiser  Sorry, but my earlier comments were incorrect.  In fact I cannot get the cassandra test tor work with this PR.  Both test cases fail.

**Comment by objectiser** [comment]
@kevinearls Ok thanks Kevin - I'll take anothe look.

**Comment by objectiser** [comment]
@kevinearls I've updated to remove the common spec from the cassandra create schema job for now - all e2e tests run fine locally except the streaming one timed out - could you try running all the tests locally to see what results you see? Thanks.

**Comment by objectiser** [comment]
@jpkrohling Looks like all is ok now :)
@kevinearls don't worry about retesting.

**Comment by jpkrohling** [comment]
LGTM! Feel free to merge if you think it's ready. Should I start the release process after this one gets merged?

**Comment by objectiser** [comment]
@jpkrohling yes I think the release should be done.

**Pull request merged**
