### PR TITLE
Fix command to deploy the simplest operator

### PR DESCRIPTION
**Pull request by geoand**
Signed-off-by: Georgios Andrianakis <geoand@gmail.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/34)

**Comment by geoand** [comment]
I did have a problem, since `run` attempts to invoke the built artifact (`./_output/bin/jaeger-operator`) which is not present if the project is not built beforehand.
Am I perhaps going about this the wrong way?

Thanks

**Comment by geoand** [comment]
@jpkrohling Sure thing, on it :)

**Comment by geoand** [comment]
@jpkrohling I updated this PR to include the `simplest` CRD command fix and opened #35 to address the `run` goal fix

**Pull request merged**
