### PR TITLE
Add container security context support

### PR DESCRIPTION
**Pull request by mjnagel**
Signed-off-by: Micah Nagel <micah.nagel@parsons.com>

## Which problem is this PR solving?
Resolves https://github.com/jaegertracing/jaeger-operator/issues/2032

## Short description of the changes
- Adds support for `containerSecurityContext` in common spec
- `containerSecurityContext` used as the security context for containers in each of agent, all-in-one, collector, ingester, query

### CODE REVIEW

**Review by iblancasa — CHANGES_REQUESTED** [review]
Please @mjnagel, could you take a look to the failed GitHub Actions Workflows?

**Review by frzifus — COMMENTED** [review]
calling `make api-docs` should fix it.

**Comment by mjnagel** [comment]
> calling `make api-docs` should fix it.

@frzifus thanks! Should be good to go now? Also rebased/squashed commits.

**Review by iblancasa — APPROVED** [review]

**Review by frzifus — COMMENTED** [review]
Should we set and verfiy some `ContainerSecurityContext` fields in the agent/collector/... unittests to make sure everything works as expected?
What do you think @mjnagel ?

**Comment by mjnagel** [comment]
> Should we set and verfiy some `ContainerSecurityContext` fields in the agent/collector/... unittests to make sure everything works as expected? What do you think @mjnagel ?

I should be able to add test(s) today if we want. I didn't think it was necessary at first since it's a direct 1:1 "passthrough" from the Jaeger spec -> deployment and issues would be exposed as build errors if there were a type mismatch. But more testing never hurts 😄

**Comment by mjnagel** [comment]
@frzifus should be good to go now. I added 2 tests to each of agent, collector, ... that validate container security context is being set and that it overrides the default "global"/common set in the spec.

**Review by frzifus — APPROVED** [review]
Awesome!

**Pull request merged**
