### PR TITLE
Custom Image Pull Policy

### PR DESCRIPTION
**Pull request by edenkoveshi**
## Which problem is this PR solving?
- This is a resubmission of this https://github.com/jaegertracing/jaeger-operator/pull/1771 after adding my ImagePullPolicy changes on top of the other PR (which has been merged since then, so on top of this repository's main branch)

## Short description of the changes
This is quite simple really.

I've added corev1.PullPolicy to the JaegerCommonSpec and then handled it within the util.Merge function
And then I have added the policy  from JaegerCommonSpec to the relevant containers being set up.

If any of them is not set, Kubernetes default is taken.

Following any other JaegerCommonSpec properties, those defined under Jaeger.Spec.JaegerCommonSpec are overwritten by the internal ones (Jaeger.Spec.Agent.JaegerCommonSpec,Jaeger.Spec.AllInOne.JaegerCommonSpec, etc.)

Test cases have been added and relevant tests updated. Also tested manually on a minikube environment.

CRD Changes:

- All deployment modes now have imagePullPolicy field, including the Jaeger object itself

### CODE REVIEW

**Review by frzifus — APPROVED** [review]
Hi @edenkoveshi, again thanks for your contribution. Your change looks good to me!

could you have a look @rubenvp8510?

We might want to include the changes in the e2e tests too. https://github.com/jaegertracing/jaeger-operator/issues/1744

**Comment by frzifus** [comment]
oh @edenkoveshi seems you need to regenerate crd files. (`make manifests` should solve it)

https://github.com/jaegertracing/jaeger-operator/runs/5360852359?check_suite_focus=true#step:6:167

**Comment by edenkoveshi** [comment]
Done.

**Review by frzifus — DISMISSED** [review]
perfect :)

**Review by rubenvp8510 — DISMISSED** [review]

**Comment by frzifus** [comment]
@edenkoveshi seems there are a few to many files overwritten :facepalm: 

https://github.com/jaegertracing/jaeger-operator/runs/5366866489?check_suite_focus=true#step:6:177

**Comment by edenkoveshi** [comment]
Looking on the command that it runs 
```
cd config/manager && /home/runner/work/jaeger-operator/jaeger-operator/bin/kustomize edit set image controller=quay.io/jaegertracing/jaeger-operator:"1.31.0"
```

Comparing this with the one in the Makefile `bundle` entry:
```
cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
	$(KUSTOMIZE) build config/manifests | $(OPERATOR_SDK) generate bundle -q --overwrite --manifests --version $(VERSION) $(BUNDLE_METADATA_OPTS)
```
This sets automatically my user as the image prefix, which is obviously different than the one running in the CI, and a version which is 1.31.0-{commit_id} which is obviously different than 1.31.0

What am I missing?

**Review by frzifus — APPROVED** [review]
LGTM :)

**Review by rubenvp8510 — APPROVED** [review]

**Pull request merged**
