### PR TITLE
Add E2E tests for more ES scenarios

### PR DESCRIPTION
**Pull request by iblancasa**
## Which problem is this PR solving?
- Add E2E tests for new scenarios when using Elasticsearch as storage in OpenShift:
   * Upstream Elasticsearch instance
   * Autoprovisioned ES instance using the Elasticsearch OpenShift Operator
   * Provision an ES instance using the Elasticsearch OpenShift Operator

All these scenarios are now supported for `es-rollover` and `es-index-cleaner` E2E tests.

## Short description of the changes
- Add templates for the new Jaeger and ES deployments
- Add new `production_managed_es` value as `deploy_mode` parameter for `render_install_jaeger` macro
- Add new parameter `deploy_mode` to `render_install_elasticsearch`
- Remove wrong `enabled` parameter from `esRollover`

### CODE REVIEW

**Comment by iblancasa** [comment]
@frzifus if you check the logs, you'll see the test are not flaky. The template generation failing. It is failing because some macros changed the accepted parameters. I have to work on it.

Please, don't merge anything with failed tests.

**Comment by frzifus** [comment]
> Please, don't merge anything with failed tests.

I can not :)

**Comment by iblancasa** [comment]
@frzifus @rubenvp8510 this PR is ready for review :)

**Comment by frzifus** [comment]
@iblancasa could you rebase?

> This branch is out-of-date with the base branch

**Pull request merged**
