### PR TITLE
Recognize when a resource has been deleted while the operator waits

### LINKED ISSUE #670: jaeger operator service is not available for a couple of minutes
I face this issue when we supply invalid options on CR file to jaeger-services.
Steps followed:
* Deploy the cr file (`oc create -f cr-file.yaml`)
* wait until all the services come up. (jaeger query service will not come up)
* undeploy jaeger services (`oc delete -f cr-file.yaml`)
* Note the jaeger-operator log
* this error continues approx 5 minutes. During this period unable to create jaeger services.

CR file: (invalid option supplied for jaeger query service)
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  strategy: production
  query:
    replicas: 1
    options:
      invalidOption: "invalid option"
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      resources:
```

Operator log:
```
time="2019-09-20T16:54:35Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=jkandasa ready=0
time="2019-09-20T16:54:36Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:54:36Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:54:36Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=jkandasa ready=0
time="2019-09-20T16:54:37Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=jkandasa ready=0
time="2019-09-20T16:54:38Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=jkandasa ready=0
time="2019-09-20T16:54:39Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=jkandasa ready=0
time="2019-09-20T16:54:40Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=jkandasa ready=0
time="2019-09-20T16:54:41Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=jkandasa
time="2019-09-20T16:54:41Z" level=debug msg="Reconciling Deployment" name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:41Z" level=debug msg="Reconciling Deployment" name=elasticsearch-cdm-jkandasajaegerqe-1 namespace=jkandasa
time="2019-09-20T16:54:41Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:54:41Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:54:41Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:42Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:43Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:44Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:45Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:46Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:54:46Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:54:46Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:47Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:48Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:49Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:50Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:51Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:54:51Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:54:51Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:52Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:53Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:54Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:55Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:56Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:54:56Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:54:56Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:57Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:58Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:54:59Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:00Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:01Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:55:01Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:55:01Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:02Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:03Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:04Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:05Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:06Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:55:06Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:55:06Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:07Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:08Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:09Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:11Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:11Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
time="2019-09-20T16:55:11Z" level=debug msg="The 'es-provision' option is explicitly set" es-provision=true
time="2019-09-20T16:55:11Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:12Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:13Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:14Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:15Z" level=debug msg="Deployment doesn't exist yet." name=jaegerqe-query namespace=jkandasa
time="2019-09-20T16:55:16Z" level=debug msg="The 'platform' option is explicitly set" platform=openshift
```

### PR DESCRIPTION
**Pull request by jpkrohling**
Fixes #670 by making the operator recognize when a resource existed before but ceases to exist while waiting for said resource to become available.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@kevinearls we had a similar problem in e2e tests before. Unfortunately, there are no unit tests that can be made to check this new code, but perhaps you could adapt the test that was failing before? It's actually easy to reproduce. This is a CR that will trigger the condition where the operator will wait indefinitely:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: fails
spec:
  allInOne:
    options:
      invalidOption: "invalid option"
```

Apply this, wait a few milliseconds and delete the CR. Before this PR, the reconciliation would fail after 5 minutes with:

```
ERRO[0317] failed to apply the changes                   error="timed out waiting for the condition" execution="2019-09-24 09:16:52.72172503 +0000 UTC" instance=fails namespace=default
```

With this PR, it fails far earlier with:

```
WARN[0012] Deployment has been removed.                  name=fails namespace=default
ERRO[0012] failed to apply the changes                   error="deployment has been removed" execution="2019-09-24 09:22:28.740323219 +0000 UTC" instance=fails namespace=default
```

@jkandasa, I published an image that can be used for manual testing this change: `quay.io/jpkroehling/jaeger-operator:670-Recognize-when-deployment-has-been-deleted`.

**Comment by kevinearls** [comment]
@jpkrohling sorry for the delay, I will be working on this today.

**Comment by kevinearls** [comment]
@jpkrohling Bizarrely, I cannot reproduce this now.  I may be overlooking something, or it may just be that whatever timing issue I was hitting before is not occurring now.  I will try again later when I have time, but it might be best to wait till @jkandasa  is back.

**Comment by kevinearls** [comment]
@jpkrohling  I was able to confirm that your CR triggers the condition, and that this PR fixes it.  So LGTM.

**Comment by jpkrohling** [comment]
Thanks! Do you think it makes sense to create an e2e test for this? If so, could you create an issue for that? I'm merging this in the meantime.

**Pull request merged**
