### PR TITLE
Use Elasticsearch provisioning from OpenShift Elasticsearch operator

### LINKED ISSUE #1707: Use certificate namagement from OpenShift Elasticserch operator
## Requirement - what kind of business use case are you trying to solve?

I want to use certificate provisioning and management from the OpenShift Elasticsearch operator. This feature reduces code in Jaeger operator and allows using a single ES cluster with multiple jaeger collectors.

An explicit installation at the moment could look like this. First provision ES and then Jaeger:

```yaml
apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
  annotations:
    logging.openshift.io/elasticsearch-cert-management: "true"
    logging.openshift.io/elasticsearch-cert.jaeger-elasticsearch: user.jaeger # this jaeger-elasticsearch secret with ca-bundle.crt, tls.crt, tls.key
  name: elasticsearch
spec:
  managementState: Managed
  nodeSpec:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
  nodes:
    - nodeCount: 1
      proxyResources: {}
      resources: {}
      roles:
        - master
        - client
        - data
      storage: {}
  redundancyPolicy: ZeroRedundancy
```

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tenant1
spec:
  strategy: production
  ingress:
    openshift:
      sar: "" # allow login for all OCP users for testing
  volumeMounts:
    - name: elastic-certs
      mountPath: /certs
  volumes:
    - name: elastic-certs
      secret:
        secretName: jaeger-elasticsearch
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elasticsearch:9200
        index-prefix: tenant1
        num-shards: 1
        num-replicas: 0
        timeout: 15s
        tls:
          enabled: true
          ca: /certs/ca-bundle.crt
          cert: /certs/tls.crt
          key: /certs/tls.key
```

The certs are provisioned by ES operator and Jaeger operator just injects them. However, this should be fully automated so let's have a look how it could look like.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Action items:
* remove `cert_generation` script
* add `spec.storage.elasticsearch.name` which points to the ES instance. The default name is `elasticsearch`
* add `spec.storage.elasticsearch.provision` - decides whether ES instance should be provisioned or not. Defaults to `true`

The ES is provisioned if `spec.storage.elasticsearch.provision=true` and `options.es.server-urls` is not defined. The ES CR name is used from `spec.storage.elasticsearch.name`. It will use `logging.openshift.io/elasticsearch-cert.jaeger-<elasticsearch-name>: user.jaeger` to create Jaeger ES certificate.

If `options.es.server-urls` is missing and `spec.storage.elasticsearch.provision=false` Jaeger operator uses ES instance from  `spec.storage.elasticsearch.name` to connect to the ES. In this case Jaeger operator will have to watch changes on ES Kind to adjust shards and replicas in Jaeger. It will use `logging.openshift.io/elasticsearch-cert.jaeger-<elasticsearch-name>: user.jaeger` for Jaeger ES certificate.

### Upgrade

The existing Jaeger instances with self-provisioned ES will have to keep working. 
Jaeger operator right now creates `<instance-name>-jaeger-elasticsearch` secret with `user.jaeger.key`, `user.jaeger.crt` and `ca.crt`. which differs from EO created secret (name is configurable via annotation `logging.openshift.io/elasticsearch-cert.<name>: user.jaeger`) `tls.key`, `tls.crt` and `ca-bundle.crt`. 

The upgrade procedure will have to upgrade storage TLS config `es.tls.*` to point to the new files.

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves #1707 

Should be merged after #1711 

This PR removes ES cert management and reuses it from ES OpenShift operator. The upgrade procedure removes ES instance and creates new one with cert-management from EO (the same approach is done in the cluster logging operator https://github.com/openshift/cluster-logging-operator/pull/1265). 

Consequentially this PR allows sharing a single ES instance by multiple Jaeger instances.

Upgrade procedure in more details:
1. upgrade procedure removes ES CR
2. reconciliation loop removes old ES secrets 
3. reconciliation loop creates new ES instance with secrets managed by EO
4. reconciliation loop restarts jaeger collector and query (because of the flag changes - certificate names) 

Note that the upgrade procedure can be tested once Jaeger components 1.31.0 are released.

Other notable changes
* added `spec.storage.elasticsearch.name` -  denotes ES instance name
* added `spec.storage.elasticsearch.doNotProvision` denotes whether ES should be provisioned or not
* added defaulting webhook
* added validating webhook
* added cert-manager for the webhook

TODOs:

- [ ] ~add ES controller and update Jaeger if node count changes~  -will be done in a separate PR - https://github.com/jaegertracing/jaeger-operator/issues/1720
- [x] remove secrets from controller
- [x] remove cert generation 
- [x] use slimer image due to openssl removal
- [x] test upgrade

Test data to deploy a single ES and two jaeger instances sharing it.
```yaml
kubectl apply -f - <<EOF
apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
  annotations:
    logging.openshift.io/elasticsearch-cert-management: "true"
    logging.openshift.io/elasticsearch-cert.jaeger-shared-es: user.jaeger
  name: shared-es
spec:
  managementState: Managed
  nodeSpec:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
  nodes:
    - nodeCount: 1
      proxyResources: {}
      resources: {}
      roles:
        - master
        - client
        - data
      storage: {}
  redundancyPolicy: ZeroRedundancy
EOF

kubectl apply -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tenant1-jaeger
spec:
  strategy: production
  query:
    strategy:
      type: RollingUpdate
  collector:
    strategy:
      type: RollingUpdate
  ingress:
    openshift:
      sar: "" # allow login for all OCP users for testing
  storage:
    type: elasticsearch
    options:
      es:
        index-prefix: tenant1
    elasticsearch:
      name: shared-es
      doNotProvision: true
      nodeCount: 1
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          memory: 1Gi
EOF

kubectl apply -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: tenant2-jaeger
spec:
  strategy: production
  query:
    strategy:
      type: RollingUpdate
  collector:
    strategy:
      type: RollingUpdate
  ingress:
    openshift:
      sar: "" # allow login for all OCP users for testing
  storage:
    type: elasticsearch
    options:
      es:
        index-prefix: tenant2
    elasticsearch:
      name: shared-es
      doNotProvision: true
      nodeCount: 1
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          memory: 1Gi
EOF
```

### CODE REVIEW

**Review by rubenvp8510 — APPROVED** [review]

**Comment by rubenvp8510** [comment]
LGTM, There is a conflict on the bundle manifest, could you rebase? 

Thanks!

**Comment by pavolloffay** [comment]
rebased

**Comment by mjnagel** [comment]
@pavolloffay / @rubenvp8510 is there a way to "disable" this new functionality via an operator start argument or anything? Unless I'm missing something it seems like `cert-manager` was added as a hard dependency for the Jaeger operator to even start up, and the only use case for certs being needed is on Openshift when using the Elastic operator. 

It seems like in the majority of deployment scenarios (i.e. anything not on openshift / anything not using the openshift elastic operator) the certs will not be used. Was any thought given to adding an option to disable this functionality? I can open a feature request if needed, just wanted to follow up on the PR here for visibility and the initial ask.

**Comment by pavolloffay** [comment]
There are coming more features that will require cert manager. All webhook based features will require it:
* https://github.com/jaegertracing/jaeger-operator/pull/1804
* we will also migrate defaulting and validating to the webhook

**Pull request merged**
