### PR TITLE
Preparing relase 1.20.0

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Review by objectiser — APPROVED** [review]

**Comment by objectiser** [comment]
@jpkrohling Approved - but test failure - worth restarting?

**Comment by jpkrohling** [comment]
@kevinearls , something seems off: 

> Error:     TestStreamingSuite/TestStreamingWithTLS: streaming_test.go:87: This test should only run when using OLM

Do you know what this is about?

**Comment by kevinearls** [comment]
@jpkrohling That's odd.  That comes from a t.Skip() statement and should certainly not be an error: https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/streaming_test.go#L87

There are other places where t.LogF is also giving errors.  I don't know what effects the log level so I don't understand why we would get that.  I think normally these should be info messages.

**Comment by jpkrohling** [comment]
I'm merging despite the test errors, as all tests passed in a previous run, except streaming. @kevinearls confirmed that the streaming failures aren't due to this PR.

**Pull request merged**
