### PR TITLE
Fix autodetect restarting platform from OpenShift to Kubernetes

### PR DESCRIPTION
**Pull request by objectiser**
Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@rubenvp8510 Would you be able to review? It is related to https://issues.redhat.com/browse/TRACING-1117

**Comment by objectiser** [comment]
cc @jpkrohling for future reference :)

**Comment by rubenvp8510** [comment]
This looks good.

**Comment by objectiser** [comment]
@kevinearls @rubenvp8510 Thanks - will merge then.

**Pull request merged**
