### PR TITLE
support image pull secrets

### LINKED ISSUE #1621: Issues setting up jaeger-operator (helm chart) with custom docker registry
**Describe the bug**
When trying to setup jaeger-operator (helm chart) with a custom docker registry it fails for *allinone* strategy. Specifically it's missing the imagePullSecrets option that's required when you use a custom registry. We're using ArgoCD to deploy our helm charts on AWS EKS. 

**To Reproduce**
1. Try to create a CRD with all in one strategy:
```
          spec:
            strategy: allInOne
            allInOne:
              image: <CUSTOM_DOCKER_REGISTRY>/jaegertracing/all-in-one:1.27
              options:
                log-level: info
              imagePullSecrets:
                - name: <SOME_SECRET>
```
2. it returns an error that it can't pull the image from the registry since it's missing the required credentials

**Expected behavior**
Being able to pull the docker image from a custom docker registry

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: latest (1.27.0) using 2.26.0 helm chart
 - Deployment: Kubernetes (EKS)

**What troubleshooting steps did you try?**
Analized the code ( https://github.com/jaegertracing/jaeger-operator/blob/66e7911177f7e85d92ad10e00ac8692306da7d7c/pkg/apis/jaegertracing/v1/jaeger_types.go#L243-L284 ) to see if there is an option for `imagepullsecrets` in `allinone` strategy - couldn't find any.

### PR DESCRIPTION
**Pull request by frzifus**
Closes #1621 

Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>

## Which problem is this PR solving?
- allows it to set ImagePullSecrets for Jaeger

## Short description of the changes
- field `ImagePullSecrets` is moved from `JaegerAgentSpec` to `JaegerCommonSpec`
- secret is used in deployment for `all_in_one strategy`
- secret is used in deployment for `agent`, `collector`, `ingester` and `query`

## Note

- [x] tested my changes again

@iblancasa Do you have a recommendation how these changes can be tested automatically?

### CODE REVIEW

**Comment by iblancasa** [comment]
@frzifus it is a good question.
For the E2E tests we are using `kind` to deploy a local cluster and `KUTTL` to run the tests. I added this info to `CONTRIBUTING.md` in #1739.
Kind has a local registry and the automation pushes the container images to that registry using the `kind load` command. After doing some research, I think the only path we have is to deploy a local registry (different than the one from kind) and configure it to use secrets :thinking:.
If you want, you can create an issue and I can invest some time to implement the test. What do you think?

**Comment by frzifus** [comment]
Sounds great, thanks. I created a new issue https://github.com/jaegertracing/jaeger-operator/issues/1744.
I'll just fix the build and then look at your pr.

**Comment by frzifus** [comment]
Finally.
```bash
kubectl apply -n observability -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: allInOne
  allInOne:
    image: docker.io/d743addb4031/jaeger-all-in-one # private 
    options:
      log-level: debug
    imagePullSecrets:
     - name: testcred
EOF
```

**Comment by rubenvp8510** [comment]
Do we need to add some unit testing for this?

**Comment by frzifus** [comment]
fair point

**Comment by frzifus** [comment]
Is [this](https://github.com/jaegertracing/jaeger-operator/runs/5166306483?check_suite_focus=true#step:3:1539) just flakiness?

**Comment by rubenvp8510** [comment]
> Is [this](https://github.com/jaegertracing/jaeger-operator/runs/5166306483?check_suite_focus=true#step:3:1539) just flakiness? (updated branch)

yes :(

**Comment by iblancasa** [comment]
@rubenvp8510 @frzifus I created #1751 to address it :). Sorry for the inconvenience.

**Review by rubenvp8510 — APPROVED** [review]

**Pull request merged**
