### PR TITLE
Join multiple E2E test suites in one

### PR DESCRIPTION
**Pull request by iblancasa**
Signed-off-by: Israel Blancas <iblancas@redhat.com>

## Which problem is this PR solving?
- Reduce the number of test suites to speedup the CI

## Short description of the changes
- Join the `istio`, `outside-cluster` and `cassandra` E2E test suites in one
- Remove `smoke-cassandra` test because it is covered in `examples::with-cassandra`

### CODE REVIEW

**Comment by iblancasa** [comment]
@rubenvp8510 can you take a look to this PR? Thanks :)

**Comment by pavolloffay** [comment]
I am not sure if merging jobs is the right approach right now. First, we should try to remove duplicates and reduce the total number of jobs.

I would suggest to remove `smoke` as it is covered in `allinone`.  This should remove two jobs.

**Comment by pavolloffay** [comment]
The generate test suite can  be executed only on single k8s version. The goal of that test is to verify the generated manifest files can are valid and deployment can be created. The other tests already cover compatibility with multiple k8s versions.

**Comment by iblancasa** [comment]
@pavolloffay The cases for `generate` and `allinone` will be covered as part of other PRs. Step by step.

I merged these 3 tests cases here because a lot of the time we consume is to prepare the workflows to execute the test suites. Since these 3 tests are "alone" in their categories (at least for now), we can merge them in a single place. In the future, we can revisit this decision if needed.

**Comment by iblancasa** [comment]
Also, removing the `smoke` test suite is covered already in #1782

**Comment by iblancasa** [comment]
@rubenvp8510 this PR is ready to be merged

**Review by rubenvp8510 — APPROVED** [review]

**Comment by frzifus** [comment]
Any idea why it doesnt continue with the checks? ping @iblancasa 
grafik

**Review by frzifus — APPROVED** [review]

**Comment by iblancasa** [comment]
@frzifus when the GitHub Actions workflows are modified, @rubenvp8510 or other maintainer needs to do some manual steps to stop the old workflows.

They will never run because they were removed

**Pull request merged**
