### PR TITLE
Preparing release v1.30.0

### PR DESCRIPTION
**Pull request by rubenvp8510**
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

### CODE REVIEW

**Comment by rubenvp8510** [comment]
@pavolloffay  @rkukura Could you please review?

Thanks

**Review by pavolloffay — DISMISSED** [review]

**Comment by rubenvp8510** [comment]
@pavolloffay Could you review this again? I've already updated.

Thanks

**Review by pavolloffay — APPROVED** [review]
The compatibility matrix should be updated as well https://github.com/jaegertracing/jaeger-operator#compatibility-matrix.

**Comment by rubenvp8510** [comment]
> The compatibility matrix should be updated as well https://github.com/jaegertracing/jaeger-operator#compatibility-matrix.

Will do this in a separate PR, I need to update the matrix with older versions also.

**Pull request merged**
