### PR TITLE
Add support for Kubernetes 1.27

### LINKED ISSUE #2232: [Feature]: add support for Kubernetes 1.27
### Requirement

Upgrade dependencies and CI to use Kubernetes 1.27

### Problem

.

### Proposal

_No response_

### Open questions

_No response_

### PR DESCRIPTION
**Pull request by iblancasa**
## Which problem is this PR solving?
- Resolves #2232

## Short description of the changes
- Upgraded `controller-gen`
- Upgraded Kubernetes libraries to v1.27.2
- Upgrade `controller-runtime` to 0.15.0
- Fix breaking changes

> **Warning**
> The unit tests are failing with some problems related to the `fakeclient`. It seems to be https://github.com/kubernetes-sigs/controller-runtime/issues/2362

> **Warning**
> The `operator-lib` dependency uses one commit instead of the latest released version (`github.com/operator-framework/operator-lib v0.11.1-0.20230607132417-ecb9be488378`) because https://github.com/operator-framework/operator-lib/issues/115

## Pending:
- [ ] Add the new Kubernetes version to the E2E tests

### CODE REVIEW

**Comment by frzifus** [comment]
This branch is not up-to-date and the CI is failing:
```
 Checking...
Go fmt, license check, or import ordering failures, run 'make format'
apis/v1/jaeger_webhook_test.go
```

**Comment by iblancasa** [comment]
> This branch is not up-to-date and the CI is failing:
> 
> ```
>  Checking...
> Go fmt, license check, or import ordering failures, run 'make format'
> apis/v1/jaeger_webhook_test.go
> ```

The CI is gonna fail anyway because of what I pointed out in the first message.

**Review by frzifus — APPROVED** [review]

**Comment by frzifus** [comment]
@rubenvp8510 can we force this?

**Comment by rubenvp8510** [comment]
> @rubenvp8510 can we force this?

Sure thing.

**Review by rubenvp8510 — APPROVED** [review]

**Pull request merged**
