### PR TITLE
kafka 2.5.0 is not supported by RH AMQ operator 1.7.x

### PR DESCRIPTION
**Pull request by jkandasa**
Signed-off-by: Jeeva Kandasamy <jkandasa@gmail.com>

* RH AMQ operator `1.7.x` is available now and kafka version `2.5.0` is not supported
* Supported Kafka versions are `2.6.0` and `2.7.0`
* strimzi-kafka-operator `0.20.1` has `2.6.0` template.

```
io.strimzi.operator.cluster.model.InvalidResourceException: Version 2.5.0 is not supported. Supported versions are: 2.6.0, 2.7.0.
```

### CODE REVIEW

**Comment by jkandasa** [comment]
@kevinearls Can you please review the changes?

**Review by kevinearls — APPROVED** [review]
LGTM

**Review by rubenvp8510 — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Comment by jkandasa** [comment]
@jpkrohling for some reason, E2E tests are failed
can you please re-run the tests?

**Comment by rubenvp8510** [comment]
is the ingress test, if we rebase to master the error should gone.

**Pull request merged**
