### PR TITLE
Add SKIP_ES_TESTS option to skip ES tests until external ES image is …

### PR DESCRIPTION
**Pull request by madeelrh**
…available for P&Z

### CODE REVIEW

**Comment by jkandasa** [comment]
@kevinearls @objectiser @jpkrohling can you please review this?
@madeelrh wants to skip external elastisecarch tests on the p/z environment. As they do not have external es image for p/z environment.

**Comment by objectiser** [comment]
@jkandasa @kevinearls there are a couple of things that concern me about this change - the test suite being disabled also include tests for spark dependencies, index clearer, etc - and if using external ES is an issue at the moment, wouldn't the other test suites that rely on the external ES also need to be disabled (i.e. streaming, auto-scale, examples2, multi-instance)? which would effectively disable most of the e2e tests.

This may require a more extreme refactor, to extract the way in which the Jaeger instance is created (whether auto or self provisioned ES and possibly Kafka???), from the tests being performed on them?

**Comment by kevinearls** [comment]
@jkandasa Do you know if self-prov ES instances work for P&Z?  If so I think it would be fairly simple to update most of the tests that currently use the static instance to use self prov instances.  I can write up an example if you think this would work.

**Comment by jkandasa** [comment]
@madeelibm can you please confirm?
Do you have RH ES operator on both P/Z environment?

**Comment by madeelrh** [comment]
@jkandasa as discussed with you before, we do have RH ES operator available for both P&Z. The ES instance created by the Operator can be accessed by an example CR, which uses certificates to access the ES instance. However, with the Jaeger self provisioned test the ES instance doesn't become Green. Some problem with node discovery, which doesn't happen, if I create ES instance manually from UI i.e. Installed Operators -> Red Hat OpenShift Jaeger -> Create Jaeger.

**Comment by kevinearls** [comment]
@madeelrh  I have a few questions:

1. Are you saying that if you create a self-provisioned Jaeger instance from the operator UI it works correctly?
2. Can you run the e2e-self-provisioned test with SAVE_LOGS=true and then attach (or email to me) the logs it creates as well as the logs for the Jaeger and ElasticSearch operators?

**Comment by madeelrh** [comment]
@kevinearls I am little bit ahead with debugging this issue. The TestSelfProvisionedESSmokeTest passed now with following changes:
--- a/test/e2e/self_provisioned_elasticsearch_test.go
+++ b/test/e2e/self_provisioned_elasticsearch_test.go
@@ -237,8 +237,10 @@ func getJaegerSimpleProd(instanceName string) *v1.Jaeger {
                                Elasticsearch: v1.ElasticsearchSpec{
                                        NodeCount: 1,
                                        Resources: &corev1.ResourceRequirements{
-                                               Limits:   corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("1Gi")},
-                                               Requests: corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("1Gi")},
+                                               Limits: corev1.ResourceList{corev1.ResourceMemory: resource.MustParse("4Gi")},
+                                               Requests: corev1.ResourceList{
+                                                       corev1.ResourceCPU:    resource.MustParse("4"),
+                                                       corev1.ResourceMemory: resource.MustParse("512Mi")},

However, TestIncreasingReplicas still fails and we need 4.6 RH ES operator to pass Replicas test. 
With one ES node, we are good with self provisioned tests. Could you change the rest of Jaeger test to use the self provisioned instance? 
Answer to your question:
1. Yes
2. I will email you logs.

**Review by frzifus — COMMENTED** [review]
is this still a thing? 

cc @iblancasa

**Comment by iblancasa** [comment]
I don't think so since the automation totally changed @frzifus

**Comment by frzifus** [comment]
ok thanks for clarification @iblancasa

**Pull request closed without merging**
