### PR TITLE
Change query service portname to 'http-query'

### LINKED ISSUE #907: Upstream connect error or disconnect/reset before headers. reset reason: connection termination
Hi,

When I try and expose Jaeger via Istio ingress gateway I get the following problem - I thought someone watching here would have an explanation. It's sure confusing the hell outta me! 

https://discuss.istio.io/t/upstream-connect-error-or-disconnect-reset-before-headers-reset-reason-connection-termination/4434

Cheers,

Andrew

### PR DESCRIPTION
**Pull request by objectiser**
Resolves #907 

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
Should we also have a look at collector. The collector ports might have the same issues e.g. zipkin and Jaeger `14268` port.

**Comment by objectiser** [comment]
@pavolloffay Collector (grpc) is already fine, not sure we would want to expose the zipkin port? If that is a requirement it could be addressed as a separate issue.

**Comment by pavolloffay** [comment]
> @pavolloffay Collector (grpc) is already fine, not sure we would want to expose the zipkin port? If that is a requirement it could be addressed as a separate issue.

For instance to collect data from clients which makes sense bc zipkin supports large ecosystem of js-client libraries.

**Comment by objectiser** [comment]
Good point - I'll submit another PR soon.

**Comment by andye2004** [comment]
I had actually just opened a PR to fix this issue but I shall close it off given this PR now exists. I hope no-one takes offence but I thought the following worth mentioning.

I would caution that the current PR doesn't take account of when the port is secured, e.g. 443/https. In my own PR I was calling a function as follows:-

```
func GetPortNameForQueryService(jaeger *v1.Jaeger) string {
	if jaeger.Spec.Ingress.Security == v1.IngressSecurityOAuthProxy {
		return "https-query"
	}
	return "http-query"
}
```

I think it would make sense to have something similar added to this PR. A couple of additional `asserts` in the `query_test.go` were added also added to my own and again probably make sense to be part of this one.

**Comment by objectiser** [comment]
@andye2004 Thanks for following up on this - would you mind rebasing your PR to add this change?

**Pull request merged**
