### PR TITLE
Apply the securityContext to the cassandraCreateSchema job

### LINKED ISSUE #1166: Allow configuring the securityContext of the CassandraCreateSchema job
Currently, the CassandraCreateSchema job does not take the securityContext specified in Jaeger.spec.securityContext into account: https://github.com/jaegertracing/jaeger-operator/blob/9cde42a9ccc291545de8cfaf7a9dbebf6b15af12/pkg/storage/cassandra_dependencies.go#L129

This causes the job not to start when running in a cluster with very restrictive PSPs.

I think this could be resolved quite easily by setting the Jaeger.spec.securityContext (globally set in the Jaeger CRD) to the Job's container/pod securityContext. I could create a PR for this, although it would be the my first time writing Go 😅

### PR DESCRIPTION
**Pull request by chgl**
Resolves #1166

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
The fix looks good, would you be able to add a test as well, to ensure we don't have a regression in the future?

**Comment by chgl** [comment]
@jpkrohling does this look ok?

**Review by jpkrohling — APPROVED** [review]
LGTM! Will merge on green.

**Comment by jpkrohling** [comment]
Thank you for your contribution!

**Comment by chgl** [comment]
Thank you and the team for making the contribution experience so smooth :). Hope this doesn't sound impatient: is there an ETA for the next release?

**Comment by jpkrohling** [comment]
You are actually lucky: we are planning a release this week.

**Comment by chgl** [comment]
Great to hear, thank you!

**Pull request merged**
