### PR TITLE
Automatically format imports

### PR DESCRIPTION
**Pull request by pavolloffay**
Following the same approach as in `/jaeger` repo

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/151)

**Comment by pavolloffay** [comment]
> If we do end up needing the script, it would probably be better suited for the .travis directory, as we don't have a scripts yet.

I will put it wherever you think it's the best. Seems odd to put things into `.travis`  which are not related to travis...


> Isn't goimports sufficient? 

From https://godoc.org/golang.org/x/tools/cmd/goimports

In addition to fixing imports, goimports also formats your code in the same style as gofmt so it can be used as a replacement for your editor's gofmt-on-save hook.

```
goimports -w $(go list ./cmd/... ./pkg/...)                                                                                                              4:52 
stat github.com/jaegertracing/jaeger-operator/cmd: no such file or directory
stat github.com/jaegertracing/jaeger-operator/cmd/manager: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/account: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/apis: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/apis/io/v1alpha1: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/cmd/start: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/cmd/version: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/config/sampling: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/configmap: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/controller: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/controller/deployment: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/controller/jaeger: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/deployment: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/ingress: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/inject: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/route: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/service: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/storage: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/strategy: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/util: no such file or directory
stat github.com/jaegertracing/jaeger-operator/pkg/version: no such file or directory
```

**Comment by pavolloffay** [comment]
@jpkrohling is there anything missing in this PR? 

I would like to be consistent with jaeger repo to provide the same source code structure. Enforcing style at build time is the only way how to check the code is properly formatted. As you can see the imports are mismatched in the current master.

**Comment by pavolloffay** [comment]
Check added

**Pull request merged**
