### PR TITLE
Change ES operator apiversion

### LINKED ISSUE #358: Failed to deploy es cluster
Tried to deploy ES cluster via elasticsearch-operator from jaeger-operator.
Jaeger-operator failed to deploy and throws the following error,
```
time="2019-04-03T15:39:22Z" level=error msg="failed to apply the changes" error="no matches for kind \"Elasticsearch\" in version \"logging.openshift.io/v1alpha1\"" execution="2019-04-03 15:39:17.005511739 +0000 UTC" instance=jaegerqe namespace=openshift-logging
```

CR File:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "512Mi"
        cpu: "1"
    options:
      log-level: info
      metrics-backend: prometheus
      collector:
        num-workers: 20
        queue-size: 20000
      es:
        bulk:
          size: 1048576
          workers: 1
          flush-interval: 200ms
        tags-as-fields:
          all: false
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      query:
        port: 16686
      es:
        timeout: 10s
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    options:
      log-level: info
      metrics-backend: prometheus
      processor:
        jaeger-compact:
          server-queue-size: 5000
          workers: 10
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    dependencies:
      enabled: false
    elasticsearch:
      image: quay.io/openshift/origin-logging-elasticsearch5:latest
      nodeCount: 3
      resources:
```

jaeger-operator log: [jaeger-operator.log](https://github.com/jaegertracing/jaeger-operator/files/3039807/jaeger-operator.log)

Rootcause maybe: There is a [recent change](https://github.com/openshift/elasticsearch-operator/blob/master/manifests/04-crd.yaml#L14) in ES operator. Jaeger-operator needs to be updated to [this change](https://github.com/openshift/elasticsearch-operator/blob/master/manifests/04-crd.yaml#L14).

### PR DESCRIPTION
**Pull request by objectiser**
Fixes #358 

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling I ran `dep ensure` and seem to have picked up some changes that are related to other PRs (e.g. openshift security). Technically this may not be required in this PR, but thought better to be up-to-date and leave it.

Have ran the e2e tests and they completed without any problems:
```
Running Smoke end-to-end tests...
ok  	github.com/jaegertracing/jaeger-operator/test/e2e	201.684s
Creating namespace default
service/cassandra created
statefulset.apps/cassandra created
Running Cassandra end-to-end tests...
ok  	github.com/jaegertracing/jaeger-operator/test/e2e	191.023s
statefulset.apps/elasticsearch created
service/elasticsearch created
Running Elasticsearch end-to-end tests...
ok  	github.com/jaegertracing/jaeger-operator/test/e2e	146.661s
namespace/openshift-logging created
customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
serviceaccount/elasticsearch-operator created
clusterrole.rbac.authorization.k8s.io/elasticsearch-operator created
clusterrolebinding.rbac.authorization.k8s.io/elasticsearch-operator-rolebinding created
customresourcedefinition.apiextensions.k8s.io/elasticsearches.logging.openshift.io created
deployment.apps/elasticsearch-operator created
Running Self provisioned Elasticsearch end-to-end tests...
ok  	github.com/jaegertracing/jaeger-operator/test/e2e	0.069s
```

**Comment by jpkrohling** [comment]
> Have ran the e2e tests and they completed without any problems:

Could you run it twice? If it works, you solved #355 as well.

**Comment by objectiser** [comment]
@jpkrohling When I run it second time, I get failure in the smoke tests. I tried this twice and got the same behaviour:
```
Running Smoke end-to-end tests...
time="2019-04-04T12:30:29+01:00" level=info msg="passing &{{Jaeger jaegertracing.io/v1} {my-jaeger  smoke-smoke-my-jaeger-1554377419    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[memory.max-traces:10000 log-level:debug]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} {{[]}} {{[]}} {  {map[]} {<nil>   } {<nil>     false false false} {<nil> 0  } {   } { {map[] map[]} 0 map[] {<nil> <nil>} }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
time="2019-04-04T12:32:35+01:00" level=info msg="passing &{{Jaeger jaegertracing.io/v1} {agent-as-daemonset  smoke-smoke-daemonset-1554377549    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {DaemonSet  {map[log-level:debug]} {[] [] map[] {map[] map[]}}} {{[]}} {{[]}} {  {map[]} {<nil>   } {<nil>     false false false} {<nil> 0  } {   } { {map[] map[]} 0 map[] {<nil> <nil>} }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
--- FAIL: TestSmoke (266.07s)
    --- FAIL: TestSmoke/smoke (266.04s)
        --- FAIL: TestSmoke/smoke/my-jaeger (130.10s)
            client.go:57: resource type RoleBinding with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) created
            client.go:57: resource type Role with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) created
            client.go:57: resource type ServiceAccount with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) created
            client.go:57: resource type Deployment with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) created
            utils.go:56: Initialized cluster resources. Namespace: smoke-smoke-my-jaeger-1554377419
            wait_util.go:61: Waiting for full availability of jaeger-operator deployment (0/1)
            wait_util.go:67: Deployment available (1/1)
            client.go:57: resource type Jaeger with namespace/name (smoke-smoke-my-jaeger-1554377419/my-jaeger) created
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            wait_util.go:52: Waiting for availability of my-jaeger deployment
            all_in_one_test.go:34: timed out waiting for the condition
            client.go:75: resource type Jaeger with namespace/name (smoke-smoke-my-jaeger-1554377419/my-jaeger) successfully deleted
            client.go:75: resource type Deployment with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) successfully deleted
            client.go:75: resource type ServiceAccount with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) successfully deleted
            client.go:75: resource type Role with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) successfully deleted
            client.go:75: resource type RoleBinding with namespace/name (smoke-smoke-my-jaeger-1554377419/jaeger-operator) successfully deleted
        --- FAIL: TestSmoke/smoke/daemonset (125.45s)
            client.go:57: resource type RoleBinding with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) created
            client.go:57: resource type Role with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) created
            client.go:57: resource type ServiceAccount with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) created
            client.go:57: resource type Deployment with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) created
            utils.go:56: Initialized cluster resources. Namespace: smoke-smoke-daemonset-1554377549
            wait_util.go:67: Deployment available (1/1)
            client.go:57: resource type Jaeger with namespace/name (smoke-smoke-daemonset-1554377549/agent-as-daemonset) created
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            wait_util.go:47: Waiting for availability of agent-as-daemonset-agent-daemonset daemonset
            daemonset.go:33: timed out waiting for the condition
            client.go:75: resource type Jaeger with namespace/name (smoke-smoke-daemonset-1554377549/agent-as-daemonset) successfully deleted
            client.go:75: resource type Deployment with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) successfully deleted
            client.go:75: resource type ServiceAccount with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) successfully deleted
            client.go:75: resource type Role with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) successfully deleted
            client.go:75: resource type RoleBinding with namespace/name (smoke-smoke-daemonset-1554377549/jaeger-operator) successfully deleted
        --- FAIL: TestSmoke/smoke/sidecar (10.49s)
            client.go:57: resource type RoleBinding with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) created
            client.go:57: resource type Role with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) created
            client.go:57: resource type ServiceAccount with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) created
            client.go:57: resource type Deployment with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) created
            utils.go:56: Initialized cluster resources. Namespace: smoke-smoke-sidecar-1554377675
            wait_util.go:67: Deployment available (1/1)
            client.go:57: resource type Jaeger with namespace/name (smoke-smoke-sidecar-1554377675/agent-as-sidecar) created
            client.go:57: resource type Deployment with namespace/name (smoke-smoke-sidecar-1554377675/vertx-create-span-sidecar) created
            wait_util.go:67: Deployment available (1/1)
            sidecar.go:30: could not find pod with image jaegertracing/all-in-one
            client.go:75: resource type Deployment with namespace/name (smoke-smoke-sidecar-1554377675/vertx-create-span-sidecar) successfully deleted
            client.go:75: resource type Jaeger with namespace/name (smoke-smoke-sidecar-1554377675/agent-as-sidecar) successfully deleted
            client.go:75: resource type Deployment with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) successfully deleted
            client.go:75: resource type ServiceAccount with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) successfully deleted
            client.go:75: resource type Role with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) successfully deleted
            client.go:75: resource type RoleBinding with namespace/name (smoke-smoke-sidecar-1554377675/jaeger-operator) successfully deleted
FAIL
FAIL	github.com/jaegertracing/jaeger-operator/test/e2e	266.139s
make: *** [Makefile:86: e2e-tests-smoke] Error 1
```

**Comment by objectiser** [comment]
@jkandasa If you get a chance, would be good if you could give the fix a quick try using `objectiser/jaeger-operator:latest` ?

**Pull request merged**
