### PR TITLE
Refined Jaeger instance injection logic

### LINKED ISSUE #1116: Sidecar injection cannot find appropriate Jaeger instance
When adding a Jaeger instance to the current namespace, I would expect the Operator to use that instance when injecting sidecars into deployments. Instead, the operator reports that it cannot find a suitable instance:

```console
$ kubectl apply -f deploy/examples/business-application-injected-sidecar.yaml 
deployment.apps/myapp created

$ kubectl logs deployments/jaeger-operator -n openshift-operators 
...
time="2020-07-06T12:29:16Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=myapp jaeger=jaeger jaeger-namespace=istio-system namespace=istio-system

$ kubectl delete deployment myapp
deployment.apps "myapp" deleted

$ kubectl apply -f deploy/examples/simplest.yaml 
jaeger.jaegertracing.io/simplest created

$ kubectl get jaegers
NAME       STATUS    VERSION   STRATEGY   STORAGE   AGE
simplest   Running   1.17.3    allinone   memory    8s

$ kubectl apply -f deploy/examples/business-application-injected-sidecar.yaml 
deployment.apps/myapp created

$ kubectl logs deployments/jaeger-operator -n openshift-operators
...
time="2020-07-06T12:35:30Z" level=info msg="No suitable Jaeger instances found to inject a sidecar" deployment=myapp
```

Workaround: changing the annotation value from `true` to `simplest` makes it correctly inject the sidecar:

```console
$ kubectl logs deployments/jaeger-operator -n openshift-operators
time="2020-07-06T12:39:12Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=myapp jaeger=simplest jaeger-namespace=bookinfo namespace=bookinfo
```

Environment:
```
$ oc version
Client Version: 4.4.9
Server Version: 4.4.9
Kubernetes Version: v1.17.1+912792b

$ kubectl logs deployments/jaeger-operator -n openshift-operators | head
time="2020-07-06T11:27:29Z" level=info msg=Versions arch=amd64 identity=openshift-operators.jaeger-operator jaeger=1.17.3 jaeger-operator=1.17.3.redhat6 operator-sdk=v0.15.1 os=linux version=go1.13.4
```

cc @rubenvp8510

### PR DESCRIPTION
**Pull request by rubenvp8510**
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

Fixes #1116

### CODE REVIEW

**Comment by rubenvp8510** [comment]
@jpkrohling please review.

**Comment by jpkrohling** [comment]
This PR isn't fixing the problem. You can reproduce it like this:

```console
$ crc start
...
Started the OpenShift cluster

$ make run
INFO[0000] Running the operator locally; watching namespace "" 
INFO[0000] Versions                                      arch=amd64 identity=default.jaeger-operator jaeger=1.18.1 jaeger-operator=v1.18.1-18-gf1f57f66 operator-sdk=v0.18.2 os=linux version=go1.14.6
I0729 10:23:30.164784   26167 request.go:621] Throttling request took 1.04514758s, request: GET:https://api.crc.testing:6443/apis/coordination.k8s.io/v1?timeout=32s
INFO[0002] Auto-detected the platform                    platform=openshift
INFO[0002] Auto-detected ingress api                     ingress-api=networking
INFO[0002] Automatically adjusted the 'es-provision' flag  es-provision=no
INFO[0002] Automatically adjusted the 'kafka-provision' flag  kafka-provision=no
INFO[0002] The service account running this operator has the role 'system:auth-delegator', enabling OAuth Proxy's 'delegate-urls' option 
INFO[0008] OAuthProxy ImageStream namespace and/or name not defined  name= namespace=
```

Then, in another terminal:
```console
$ kubectl apply -f deploy/examples/business-application-injected-sidecar.yaml 
deployment.apps/myapp created
```

In the first terminal, you'll see this:

```console
INFO[0010] No suitable Jaeger instances found to inject a sidecar  deployment=myapp
INFO[0010] No suitable Jaeger instances found to inject a sidecar  deployment=myapp
INFO[0013] No suitable Jaeger instances found to inject a sidecar  deployment=myapp
```

**Comment by jpkrohling** [comment]
By the way, the steps above can also be reproduced with a regular `minikube` installation.

**Comment by jpkrohling** [comment]
My bad: as you pointed out, I forgot one crucial step: the actual Jaeger instance :-) This PR does fix the reported issue.

**Comment by rubenvp8510** [comment]
:coffee:

**Pull request merged**
