### PR TITLE
Fix unstable mod tidy

### LINKED ISSUE #1326: Unable to lock version for indirect dependency
As we have discussed in PR #1319, I tried to run `go mod tidy` on the master branch and the indirect version of `github.com/miekg/dns@v1.1.35` went away. This dependency is introduced in #1298 intended to fix a CVE issue.

I suppose as per https://github.com/golang/go/issues/40784#issuecomment-675161073, it is not possible to lock/pin an indirect dependency. So we have to be very careful with this indirect dep.

Just a comment. I am not sure what we can do now. Maybe add a git-hook to ensure? @jpkrohling

### PR DESCRIPTION
**Pull request by lujiajing1126**
Fix #1326 

Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
Looks good, but can you find a way to provide a positive confirmation that this is indeed the version being included? Running `go mod graph | grep dns` shows all versions that our dependencies use for this, so, it wouldn't help much I think...

**Comment by lujiajing1126** [comment]
> Looks good, but can you find a way to provide a positive confirmation that this is indeed the version being included? Running `go mod graph | grep dns` shows all versions that our dependencies use for this, so, it wouldn't help much I think...

After some investigation, I find that "github.com/miekg/dns" module does not exist in the binary built with `make gobuild` at all. So I think it is safe to run `go mod tidy` to make a cleanup.

I have tested with both `objdump` and `go tool objdump`.

**Comment by jpkrohling** [comment]
Sounds good to me. We might want to get an approval from @objectiser as well, as it was introduced by him some time ago.

**Comment by objectiser** [comment]
The second commit, where the dependency is listed in the `replace` section, seemed ok - but without that it reverts the version of the dependency which is affected by the CVE. What was the issue with the second commit?

**Comment by lujiajing1126** [comment]
> The second commit, where the dependency is listed in the `replace` section, seemed ok - but without that it reverts the version of the dependency which is affected by the CVE. What was the issue with the second commit?

The affected module "github.com/miekg/dns" seems not appear in the generated binary. So I suppose it is safe to run `go mod tidy` here.

**Review by objectiser — APPROVED** [review]

**Pull request merged**
