### PR TITLE
Enable JAEGER_SERVICE_NAME and JAEGER_PROPAGATION env vars to be set …

### LINKED ISSUE #29: Could agent sidecar injection specify service name
Wondering if, when an agent sidecar is injected, whether it could also specify the JAEGER_SERVICE_NAME environment variable on the service?

This would avoid user having to manually add it, and also means that we could define the convention - e.g. <name>.<namespace>, if we wanted to support multitenancy.

As a side issue - should the injection be dependent upon an annotation? Similar to Istio sidecar injection which can be enabled on the namespace (so all deployments) or individually? Just so that users have some control, and not everything automatically gets a jaeger agent sidecar.

### LINKED ISSUE #74: Agent sidecar injection: enable propagation env var to be set
If automatic agent sidecar injection is used within an Istio environment, then it would be useful to be able to set the JAEGER_PROPAGATION environment variable to B3.

To enable this to be more generic, we should just enable the agent configuration to include setting the propagation value.

This requirement is similar to #29, which sets the service name env var when auto-injecting the agent sidecar.

### PR DESCRIPTION
**Pull request by objectiser**
…on containers with injected agent

Resolves #29 
Resolves #74

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/128)

**Comment by objectiser** [comment]
Ran e2e tests - daemonset still failing but all other tests fine. Want to try it out on a real example before merge - hopefully first thing next week.

One point - setting JAEGER_PROPAGATION to `jaeger,b3` to enable services to work in Istio environment (requiring b3) as well as non-Istio environments using the jaeger propagation format. If we had a way to know that we are running in Istio, or have Istio specific platform values (e.g. `istio` for Istio on k8s, `openshift+istio` for Istio running on openshift) then we could just specify the `b3` format in those Istio cases - and not set the env var otherwise?

**Comment by objectiser** [comment]
Created #130 for the doc issue.

How realistic do you think that use case would be? If a service developer took that approach, not sure where they would get the service name from, except a custom config property - in which case, they would probably just use that approach anyway, instead of the Jaeger env vars?

**Comment by jpkrohling** [comment]
> How realistic do you think that use case would be?

Good question. Let's record it and see if there's demand for that.

**Pull request merged**
