### PR TITLE
Add E2E testing for Rollover ES feature

### PR DESCRIPTION
**Pull request by iblancasa**
## Which problem is this PR solving?
Add E2E testing to the Rollover ES feature implemented in #267

## Short description of the changes
* Added smoke E2E Test for the Rollover ES feature
* Added E2E Test to check everything works properly when the feature is enabled after the deployment
*  Added E2E Test to check the correct indices are created when the feature is enabled before the deployment
* Extract some common logic from the ES index test suite to reuse some logic in the Rollover ES test

### CODE REVIEW

**Comment by iblancasa** [comment]
Todo:
* Add testing for the `readTTL` parameter

**Comment by jkandasa** [comment]
@iblancasa you have to sign off your commit. See the details of **DCO**

**Review by jpkrohling — COMMENTED** [review]
New e2e tests should be written using kuttl. 

See https://github.com/jaegertracing/jaeger-operator/tree/master/tests/e2e

**Comment by iblancasa** [comment]
@jpkrohling, ok I'll rewrite the tests using `kuttl`

**Pull request closed without merging**
