### PR TITLE
Add rollover support

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

This at the moment does not work with self-provisioned ES due to curator settings: https://github.com/openshift/origin-aggregated-logging/pull/1517

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/267)

**Comment by jpkrohling** [comment]
This will conflict with #265. Please wait to work on this, let's get that one merged first.

**Comment by pavolloffay** [comment]
Test CR
```
# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        use-aliases: true
```

Self-provisioned ES does not at the moment - my PR with SG config has been merged but the image is not yet available.

**Comment by pavolloffay** [comment]
this is ready for re-review

**Comment by pavolloffay** [comment]
> Why don't you just use Seconds()? time.ParseDuration("1m30s").Seconds() returns 90, so, you can just use something like return pythonUnits{units: seconds, count: int(time.ParseDuration("1m30s").Seconds())}

I am with what is there now, it's easier to read/debug.

**Comment by pavolloffay** [comment]
> .WithField("readTTL", jaeger.Spec.Storage.Rollover.ReadTTL) so that the user knows what we attempted to parse.

the value is present I have modified the logging to produce nicer logs :)

**Pull request merged**
