### PR TITLE
Factor out ingress from all-in-one and query, as common to both but i…

### PR DESCRIPTION
**Pull request by objectiser**
…s independent of either deployment strategy

This change was made as currently the [NewQueryIngress](https://github.com/jaegertracing/jaeger-operator/blob/master/pkg/ingress/query.go#L15) method takes a `JaegerSpec` but no indication of whether the config is under all-in-one or query.

One possibility would be to just supply the `JaegerIngressSpec` to this method - but the ingress is a separate component so I think it is better if factored out.

Only other question - currently the config is under top level `ingress` node - but the code has been structured based on it being an ingress for the query endpoint. If we expect other service endpoints to be exposed via an ingress, then we might want to have something like:

```
spec:
  ingress:
    query:
      enabled: true
```

Let me know thoughts on this change, and whether it would be better to remain open to other ingresses.

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/91)

**Comment by objectiser** [comment]
@jpkrohling After your comment about `make generate` on the other PR, I tried it on this one - but had to install the operator SDK. Once done I ran `make generate` but got the following error:

```
2018/11/06 18:58:07 must run command in project root dir: stat ./build/Dockerfile: no such file or directory
make: *** [Makefile:87: generate] Error 1
```

Could this be because the operator has changed?

**Comment by jpkrohling** [comment]
> Could this be because the operator SDK has changed?

Could be -- are you running the Operator SDK 0.0.7?

**Comment by objectiser** [comment]
I used the instructions in CONTRIBUTING.adoc - so it is based on master. I will try with 0.0.7.

**Comment by objectiser** [comment]
Yes that worked - I rebased on your generate change and ran the command, but there were no additional changes, which I guess is correct as all it did was move the Ingress spec.

**Comment by jpkrohling** [comment]
Great, would you mind sending a PR with the change to the CONTRIBUTING?

**Comment by objectiser** [comment]
Will do.

**Pull request merged**
