### PR TITLE
Fixed permissions for ServiceMonitor objects

### LINKED ISSUE #804: Jaeger Operator throws a warning "Could not create ServiceMonitor object"
I installed jaeger operator 1.15.0 on Openshift 4.2 environment.
I see the following warning on the jaeger-operator log. 
I do not see any impact on jaeger service deployment.

##### OCP cluster detail:
```
$ oc version
Client Version: v4.2.0
Server Version: 4.2.4
Kubernetes Version: v1.14.6+dc8862c
```

##### Jaeger-operator log:
```
time="2019-12-04T10:41:35Z" level=info msg=Versions arch=amd64 identity=openshift-operators.jaeger-operator jaeger=1.15.0 jaeger-operator=v1.15.0 operator-sdk=v0.11.0 os=linux version=go1.12.10
time="2019-12-04T10:41:41Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-12-04T10:41:41Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=yes
time="2019-12-04T10:41:41Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=yes
time="2019-12-04T10:41:41Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2019-12-04T10:41:57Z" level=warning msg="Could not create ServiceMonitor object" error="an empty namespace may not be set during creation"
```

##### oc describe pod:
```
$ oc get pods
NAME                             READY   STATUS    RESTARTS   AGE
jaeger-operator-f47c4fbd-x7mnp   1/1     Running   0          13m

$ oc describe pod jaeger-operator-f47c4fbd-x7mnp
Name:               jaeger-operator-f47c4fbd-x7mnp
Namespace:          openshift-operators
Priority:           0
PriorityClassName:  <none>
Node:               ocp4-jqe2-4vh42-worker-ccc7l/192.168.0.26
Start Time:         Wed, 04 Dec 2019 16:11:12 +0530
Labels:             name=jaeger-operator
                    pod-template-hash=f47c4fbd
Annotations:        alm-examples:
                      [
                        {
                          "apiVersion": "jaegertracing.io/v1",
                          "kind": "Jaeger",
                          "metadata": {
                            "name": "jaeger-all-in-one-inmemory"
                          }
                        },
                        {
                          "apiVersion": "jaegertracing.io/v1",
                          "kind": "Jaeger",
                          "metadata": {
                            "name": "jaeger-all-in-one-local-storage"
                          },
                          "spec": {
                            "storage": {
                              "options": {
                                "badger": {
                                  "directory-key": "/badger/key",
                                  "directory-value": "/badger/data",
                                  "ephemeral": false
                                }
                              },
                              "type": "badger",
                              "volumeMounts": [
                                {
                                  "mountPath": "/badger",
                                  "name": "data"
                                }
                              ],
                              "volumes": [
                                {
                                  "emptyDir": {},
                                  "name": "data"
                                }
                              ]
                            }
                          }
                        },
                        {
                          "apiVersion": "jaegertracing.io/v1",
                          "kind": "Jaeger",
                          "metadata": {
                            "name": "jaeger-prod-elasticsearch"
                          },
                          "spec": {
                            "storage": {
                              "options": {
                                "es": {
                                  "server-urls": "http://elasticsearch.default.svc:9200"
                                }
                              },
                              "type": "elasticsearch"
                            },
                            "strategy": "production"
                          }
                        }
                      ]
                    capabilities: Deep Insights
                    categories: Logging & Tracing
                    certified: false
                    containerImage: docker.io/jaegertracing/jaeger-operator:1.15.0
                    createdAt: 2019-09-04T13:28:40+00:00
                    description: Provides tracing, monitoring and troubleshooting microservices-based distributed systems
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "openshift-sdn",
                          "interface": "eth0",
                          "ips": [
                              "10.128.2.51"
                          ],
                          "default": true,
                          "dns": {}
                      }]
                    olm.operatorGroup: global-operators
                    olm.operatorNamespace: openshift-operators
                    olm.targetNamespaces: 
                    repository: https://github.com/jaegertracing/jaeger-operator
                    support: Jaeger
Status:             Running
IP:                 10.128.2.51
Controlled By:      ReplicaSet/jaeger-operator-f47c4fbd
Containers:
  jaeger-operator:
    Container ID:  cri-o://e0a15d769d82d7028115de82080783a29dfb17ae3973e1f7d4840e5fc1b7c84e
    Image:         jaegertracing/jaeger-operator:1.15.0
    Image ID:      docker.io/jaegertracing/jaeger-operator@sha256:497958a5c54e8e50bae28337afcf388c5a45e22c8b90ff6a1cade11793c07b52
    Port:          8383/TCP
    Host Port:     0/TCP
    Args:
      start
    State:          Running
      Started:      Wed, 04 Dec 2019 16:11:35 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      WATCH_NAMESPACE:   (v1:metadata.annotations['olm.targetNamespaces'])
      POD_NAME:         jaeger-operator-f47c4fbd-x7mnp (v1:metadata.name)
      POD_NAMESPACE:    openshift-operators (v1:metadata.namespace)
      OPERATOR_NAME:    jaeger-operator
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from jaeger-operator-token-pg7kt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  jaeger-operator-token-pg7kt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  jaeger-operator-token-pg7kt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                                   Message
  ----    ------     ----  ----                                   -------
  Normal  Scheduled  13m   default-scheduler                      Successfully assigned openshift-operators/jaeger-operator-f47c4fbd-x7mnp to ocp4-jqe2-4vh42-worker-ccc7l
  Normal  Pulling    13m   kubelet, ocp4-jqe2-4vh42-worker-ccc7l  Pulling image "jaegertracing/jaeger-operator:1.15.0"
  Normal  Pulled     13m   kubelet, ocp4-jqe2-4vh42-worker-ccc7l  Successfully pulled image "jaegertracing/jaeger-operator:1.15.0"
  Normal  Created    13m   kubelet, ocp4-jqe2-4vh42-worker-ccc7l  Created container jaeger-operator
  Normal  Started    13m   kubelet, ocp4-jqe2-4vh42-worker-ccc7l  Started container jaeger-operator
```

### PR DESCRIPTION
**Pull request by jpkrohling**
This PR fixes the permissions problems related to the creation of `ServiceMonitor` objects. After this PR, this is how a Jaeger Operator bootstrap looks like:

```
$ kubectl logs jaeger-operator-798b484d4b-zssb6 -f
time="2019-12-17T10:05:19Z" level=info msg=Versions arch=amd64 identity=openshift-marketplace.jaeger-operator jaeger=1.15.1 jaeger-operator=v1.15.1-29-g08132f63 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2019-12-17T10:05:23Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-12-17T10:05:23Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2019-12-17T10:05:23Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2019-12-17T10:05:23Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
```

If the pod is killed and a new operator is started in the same namespace, the following is seen:
```
$ kubectl logs -f jaeger-operator-798b484d4b-tdfrg
time="2019-12-17T10:11:33Z" level=info msg=Versions arch=amd64 identity=openshift-marketplace.jaeger-operator jaeger=1.15.1 jaeger-operator=v1.15.1-29-g08132f63 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2019-12-17T10:11:37Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-12-17T10:11:37Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2019-12-17T10:11:37Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2019-12-17T10:11:37Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2019-12-17T10:11:44Z" level=warning msg="could not create ServiceMonitor object" error="servicemonitors.monitoring.coreos.com \"jaeger-operator-metrics\" already exists"
```

Fixes #804.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@jkandasa I tested this on a real OpenShift 4.2.2 cluster, but would you please also give this one a test?

**Comment by jkandasa** [comment]
@jpkrohling sure, can you please share the image details?

**Comment by jpkrohling** [comment]
Yes, sorry. Here it is: `quay.io/jpkroehling/jaeger-operator:Bootstrap-warnings-1`

**Comment by jpkrohling** [comment]
@pavolloffay, @objectiser I think this one should be included for 1.16.0. Given that it only adds permissions, I'd say that the risk of breaking things is low.

**Comment by jpkrohling** [comment]
I'm merging, but I'm ready to go back to this in case @jkandasa finds any problems.

**Comment by jkandasa** [comment]
@jpkrohling I installed this operator,

Initial log:
```
time="2019-12-17T15:44:53Z" level=info msg=Versions arch=amd64 identity=openshift-operators.jaeger-operator jaeger=1.15.1 jaeger-operator=v1.15.1-29-g08132f63 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2019-12-17T15:44:57Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-12-17T15:44:57Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=yes
time="2019-12-17T15:44:57Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2019-12-17T15:44:57Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
```

I killed the pod and the log from recreated pod:
```
time="2019-12-17T15:46:39Z" level=info msg=Versions arch=amd64 identity=openshift-operators.jaeger-operator jaeger=1.15.1 jaeger-operator=v1.15.1-29-g08132f63 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2019-12-17T15:46:43Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-12-17T15:46:43Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=yes
time="2019-12-17T15:46:43Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2019-12-17T15:46:43Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2019-12-17T15:46:49Z" level=warning msg="could not create ServiceMonitor object" error="servicemonitors.monitoring.coreos.com \"jaeger-operator-metrics\" already exists"
```

I deployed all-in-one jaeger service and see the following error message. I do not see any impact on jaeger service deployment. Keep on reporting this error
```
time="2019-12-17T15:46:39Z" level=info msg=Versions arch=amd64 identity=openshift-operators.jaeger-operator jaeger=1.15.1 jaeger-operator=v1.15.1-29-g08132f63 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2019-12-17T15:46:43Z" level=info msg="Auto-detected the platform" platform=openshift
time="2019-12-17T15:46:43Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=yes
time="2019-12-17T15:46:43Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2019-12-17T15:46:43Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2019-12-17T15:46:49Z" level=warning msg="could not create ServiceMonitor object" error="servicemonitors.monitoring.coreos.com \"jaeger-operator-metrics\" already exists"
time="2019-12-17T15:47:25Z" level=info msg="Storage type not provided. Falling back to 'memory'" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:26Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:24.893052246 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:53Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:27.302253329 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:54Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:54.364018319 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:55Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:55.433833947 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:56Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:56.501854464 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:57Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:57.573294156 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:58Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:58.638006756 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:47:59Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:47:59.704821032 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:48:00Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:48:00.76602494 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:48:02Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:48:02.108547694 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:48:04Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:48:04.732970349 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:48:09Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:48:09.915670434 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:48:20Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:48:20.216807852 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2019-12-17T15:48:40Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaegerqe)" execution="2019-12-17 15:48:40.762705942 +0000 UTC" instance=jaegerqe namespace=jkandasa
```

**Pull request merged**
