### PR TITLE
WIP - Added scorecard target

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/349)

**Comment by jpkrohling** [comment]
Example output:

```console
$ make scorecard 
Context "minikube" modified.
Formatting code...
Building...
Pushing image jpkroehling/jaeger-operator:v1.11.0-2-g91fb168...
WARNING: Scorecard only works for the committed changes.
WARN[0000] Could not load config file; using flags      
Checking for existence of spec and status blocks in CR
Checking that writing into CRs has an effect
Checking if all CRDs have validation
Checking for CRD resources
Checking for existence of example CRs
Checking spec descriptors
Checking status descriptors
Basic Operator:
	Spec Block Exists: 1/1 points
	Status Block Exist: 1/1 points
	Writing into CRs has an effect: 1/1 points
OLM Integration:
	Provided APIs have validation: 0/2 points
	Owned CRDs have resources listed: 2/2 points
	CRs have at least 1 example: 1/1 points
	Spec fields with descriptors: 0/13 points
	Status fields with descriptors: N/A (depends on an earlier test that failed)

Total Score: 6/21 points
SUGGESTION: Add CRD validation for Jaeger/v1alpha1
SUGGESTION: Add CRD validation for Jaeger/v1
SUGGESTION: Add a spec descriptor for collector
SUGGESTION: Add a spec descriptor for ingester
SUGGESTION: Add a spec descriptor for query
SUGGESTION: Add a spec descriptor for storage
SUGGESTION: Add a spec descriptor for strategy
SUGGESTION: Add a spec descriptor for volumes
SUGGESTION: Add a spec descriptor for agent
SUGGESTION: Add a spec descriptor for allInOne
SUGGESTION: Add a spec descriptor for ingress
SUGGESTION: Add a spec descriptor for resources
SUGGESTION: Add a spec descriptor for sampling
SUGGESTION: Add a spec descriptor for ui
SUGGESTION: Add a spec descriptor for volumeMounts
```

The very first run after a `minikube start` still gives me an improper output:

```console
$ make scorecard 
namespace/observability created
Context "minikube" modified.
Formatting code...
Building...
Pushing image jpkroehling/jaeger-operator:v1.11.0-2-g91fb168...
WARNING: Scorecard only works for the committed changes.
WARN[0000] Could not load config file; using flags      
Checking for existence of spec and status blocks in CR
Checking that writing into CRs has an effect
Checking if all CRDs have validation
Checking for CRD resources
Checking for existence of example CRs
Checking spec descriptors
Checking status descriptors
Basic Operator:
	Spec Block Exists: 0/1 points
	Status Block Exist: 0/1 points
	Writing into CRs has an effect: 1/1 points
OLM Integration:
	Provided APIs have validation: 0/2 points
	Owned CRDs have resources listed: 2/2 points
	CRs have at least 1 example: 1/1 points
	Spec fields with descriptors: N/A (depends on an earlier test that failed)
	Status fields with descriptors: N/A (depends on an earlier test that failed)

Total Score: 4/8 points
SUGGESTION: Add a 'spec' field to your Custom Resource
SUGGESTION: Add a 'status' field to your Custom Resource
SUGGESTION: Add CRD validation for Jaeger/v1alpha1
SUGGESTION: Add CRD validation for Jaeger/v1
```

As far as I understand, this is due to some timeout in the Operator SDK.

**Comment by jpkrohling** [comment]
I'm marking this as WIP, as I'll sync this with the one from Operator Hub.

**Comment by objectiser** [comment]
@jpkrohling Was going to suggest the same thing - would like this csv to be the working copy that is updated on release, and then ideally just copied over (and renamed) to the version specific csv file in operator hub.

**Comment by jpkrohling** [comment]
I'm closing this one, as we'd probably need to change it quite a bit to make it up to date.

**Pull request closed without merging**
