### PR TITLE
readme with k8s docs instead of coreos doc about operator

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by objectiser** [comment]
@dzmitry-lahoda Thanks for the PR. You will need to sign your comment - see https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md#certificate-of-origin---sign-your-work for instructions on how to amend you commit.

@jpkrohling We need to update the instructions on signing in this repo - as the text is not as explicit as in the jaeger repo - also the referenced DCO file is missing.

**Comment by dzmitry-lahoda** [comment]
cool, broke sign off

**Comment by jpkrohling** [comment]
You can probably just run these commands:

```console
$ git rebase HEAD~5 --signoff
$ git push --force-with-lease origin patch-3
```

The sign-off is per commit, and apparently three of the commits aren't signed off.

**Comment by jpkrohling** [comment]
By the way, one of the commits has the following inconsistency:

```
 Commit sha: 5466152, Author: Dzmitry Lahoda, Committer: GitHub; Expected "Dzmitry Lahoda dzmitry.lahoda@gmail.com", but got "Dzmitry A Lahoda dzmitry.lahoda@gmail.com".
```

**Pull request merged**
