### PR TITLE
Use GOPATH instead of hardcoded path for format task

### LINKED ISSUE #811: Make format hardcodes path to goimports
https://github.com/jaegertracing/jaeger-operator/blob/43401317a305ca8220fc117b735175977e31a025/.ci/format.sh#L3

Not everybody sets `GO_ROOT` to `${HOME}/go`. Introduced in #780

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves #811 

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
GOPATH might not be set in the environment, which is why the CI jobs are failing for this PR. You might need something like this:

```diff
$ git diff
diff --git a/Makefile b/Makefile
index cf86684b..276335b8 100644
--- a/Makefile
+++ b/Makefile
@@ -44,7 +44,7 @@ ensure-generate-is-noop: generate
 .PHONY: format
 format:
        @echo Formatting code...
-       @.ci/format.sh
+       @GOPATH=${GOPATH} .ci/format.sh
 
 .PHONY: lint
 lint:
```

Without this diff, I get this error (as I don't have GOPATH set):

```console
$ make format
Formatting code...
.ci/format.sh: line 3: /bin/goimports: No such file or directory
make: *** [Makefile:47: format] Error 127
$
```

With the diff:
```console
$ make format
Formatting code...
$
```

**Comment by pavolloffay** [comment]
I didn't realize it is defined only in the makefile. I would rather move the format command to make. Other one-liner targets are defined directly there.

**Comment by pavolloffay** [comment]
> I would rather move the format command to make. Other one-liner targets are defined directly there.

Since there are comments in `Formatting..` this would require splitting the format into two targets. I will keep it as it is.

**Comment by jpkrohling** [comment]
CI build is still failing, as `make check` is failing:

```console
$ make check
Checking...
.ci/format.sh: line 3: /bin/goimports: No such file or directory
make: *** [Makefile:37: check] Error 127
```

**Comment by pavolloffay** [comment]
that is unfortunate, I will fix that

**Pull request merged**
