### PR TITLE
Add consolelink permissions to cluster role

### PR DESCRIPTION
**Pull request by rubenvp8510**
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
Could you run the "generate CSV" command and see if the next CSV will include this change? The release script has a step where it generates the CSV for the new version, you can use that as reference.

**Comment by rubenvp8510** [comment]
I ran this command:

` operator-sdk generate csv --csv-channel=stable --csv-version="1.19.1" --from-version="1.19.0" `

And it seems like the change is included on the manifest.

**Comment by jpkrohling** [comment]
@kevinearls, @rubenvp8510, there's a failing test. Is it a known issue?

**Comment by jpkrohling** [comment]
```
    TestDaemonSetSuite/TestDaemonSet: daemonset_test.go:151: 
        	Error Trace:	daemonset_test.go:151
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestDaemonSetSuite/TestDaemonSet
        	Messages:   	Failed waiting for expected content
```

@rubenvp8510, could you rebase the PR? This test failure has been fixed in the latest master.

**Comment by rubenvp8510** [comment]
Rebased,  is green now

**Pull request merged**
