### PR TITLE
Add support for ImagePullSecrets in cronjobs

### PR DESCRIPTION
**Pull request by alexandrevilain**
## Which problem is this PR solving?

The CRD allows ImagePullSecrets for esIndexCleaner or SparkDependencies but they are not used when rendering cronjobs specs.

## Short description of the changes

This change adds support for image pull secrets in cronjobs.

### CODE REVIEW

**Review by frzifus — APPROVED** [review]
awesome!

**Review by rubenvp8510 — APPROVED** [review]

**Comment by alexandrevilain** [comment]
Hi :) Do I need to update the branch another time to allow you to merge this pull request ?

**Comment by frzifus** [comment]
> [rubenvp8510](https://github.com/rubenvp8510) enabled auto-merge (squash) [yesterday](https://github.com/jaegertracing/jaeger-operator/pull/1935#event-6757249853)

hi @alexandrevilain, yes just click on update branch and it should be merged automatically after the ci passed again.

**Comment by alexandrevilain** [comment]
Hi @rubenvp8510 It seems the CI does not start due to "First-time contributors need a maintainer to approve running workflows."

**Comment by frzifus** [comment]
oh i will take care

**Pull request merged**
