### PR TITLE
Add query ingress enable switch

### PR DESCRIPTION
**Pull request by secat**
This PR addresses issue #30.

Update the jaeger query specification with an ingress specification containing an enable flag. When not set, defaults to creating the query ingress object resource.

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/36)

**Comment by secat** [comment]
___
*[pkg/apis/io/v1alpha1/types.go, line 43 at r1](https://reviewable.io/reviews/jaegertracing/jaeger-operator/36#-LMvEDHkDy0_OMLXLW7i:-LMvj-k684wUI0G9n4Xc:bs7ivdm) ([raw file](https://github.com/jaegertracing/jaeger-operator/blob/db47374c4f005ff3d7e9ed20a3d8c497b19b06cd/pkg/apis/io/v1alpha1/types.go#L43)):*
<details><summary><i>Previously, jpkrohling (Juraci Paixão Kröhling) wrote…</i></summary><blockquote>

This struct could probably be named `JaegerIngressSpec` instead of `JaegerQueryIngressSpec`. If we ever need it for the collector or for a future new component, we could reuse it.
</blockquote></details>

Excellent idea, I will make the change.

**Comment by secat** [comment]
___
*[pkg/apis/io/v1alpha1/types.go, line 51 at r1](https://reviewable.io/reviews/jaegertracing/jaeger-operator/36#-LMvETKy7t2ZQlxfAQZy:-LMvjC6kBJIyJM8qCEve:b-4b5d4o) ([raw file](https://github.com/jaegertracing/jaeger-operator/blob/db47374c4f005ff3d7e9ed20a3d8c497b19b06cd/pkg/apis/io/v1alpha1/types.go#L51)):*
<details><summary><i>Previously, jpkrohling (Juraci Paixão Kröhling) wrote…</i></summary><blockquote>

Any reason to have it as a pointer?
</blockquote></details>

It is in order to not break the default behavior. Currently a user doesn't have to specify if the ingress is enabled, it is by default.

Also, using a pointer helps detecting that case, i.e. if the flag is set or not. A `nil` pointer means it was not set, therefore use the default value.

If we do not use a pointer, the default value will be `false` if the user doesn't set the flag value.

Which direction should we go?

**Comment by secat** [comment]
___
*[pkg/apis/io/v1alpha1/types.go, line 43 at r1](https://reviewable.io/reviews/jaegertracing/jaeger-operator/36#-LMvEDHkDy0_OMLXLW7i:-LMwBkVP2hdTbQiKoPjG:brotd86) ([raw file](https://github.com/jaegertracing/jaeger-operator/blob/db47374c4f005ff3d7e9ed20a3d8c497b19b06cd/pkg/apis/io/v1alpha1/types.go#L43)):*
<details><summary><i>Previously, secat (Serge Catudal) wrote…</i></summary><blockquote>

Excellent idea, I will make the change.
</blockquote></details>

I have pushed a commit which renames the struct from `JaegerQueryIngressSpec` to `JaegerIngressSpec`.

**Comment by jpkrohling** [comment]
Thanks!

**Pull request merged**
