### PR TITLE
Add resource defs to jaeger agent sidecar

### LINKED ISSUE #160: Cannot use HorizontalPodAutoscaling: injected agent lacks resource defs
The kube-controller-manager can't autoscale our deployments with an injected Jaeger agent, as the injected container defines no CPU or Memory requests and/or limits.  

```
kube-controller-manager-ip-10-0-1-4.us-east-2.compute.internal kube-controller-manager E1205 19:17:47.410801       1 horizontal.go:188] failed to compute desired number of replicas based on listed metrics for Deployment/default/podredacted: failed to get cpu utilization: missing request for cpu on container jaeger-agent in pod default/podredacted
kube-controller-manager-ip-10-0-1-4.us-east-2.compute.internal kube-controller-manager I1205 19:17:47.410855       1 event.go:221] Event(v1.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"default", Name:"podredacted", UID:"c393ace0-cbd6-11e7-9783-021516797582", APIVersion:"autoscaling/v2beta1", ResourceVersion:"161801118", FieldPath:""}): type: 'Warning' reason: 'FailedGetResourceMetric' missing request for cpu on container jaeger-agent in pod default/podredacted
```

### PR DESCRIPTION
**Pull request by annanay25**
Resolves #160 

Needs a discussion on what the default values of the sidecar should be, and if its okay for these defaults to appear directly in the `sidecar` package.

Signed-off-by: Annanay <annanay.a@media.net>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/169)

**Comment by annanay25** [comment]
Just need to punch in the numbers for default values now.

**Comment by annanay25** [comment]
Updated. @jpkrohling

**Comment by jpkrohling** [comment]
> So for 128MiB, we would actually have to put 128 * 1024 * 1024 ?

Apparently, you could use `resource.NewScaledQuantity(128, resource.Mega)`

**Comment by jpkrohling** [comment]
@annanay25, are you still working on this one?

**Comment by annanay25** [comment]
Facing minikube setup issues, could you tell me the current test failure output? I'll work backwards from there.

**Comment by jpkrohling** [comment]
It's currently failing on the sidecar test, timing out because the last condition never becomes true (`len(resp.Data) > 0`).

**Comment by jpkrohling** [comment]
@annanay25 Any news on this one?

**Comment by jpkrohling** [comment]
Debugging this test further revealed this from the operator's logs:

```
time="2019-03-25T14:09:08Z" level=info msg="Injecting Jaeger Agent sidecar" deployment=vertx-create-span-sidecar jaeger=agent-as-sidecar jaeger-namespace=smoke-smoke-sidecar-1553522890 namespace=smoke-smoke-sidecar-1553522890
time="2019-03-25T14:09:08Z" level=error msg="failed to update" deployment="&Deployment{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:vertx-create-span-sidecar,GenerateName:,Namespace:smoke-smoke-sidecar-1553522890,SelfLink:/apis/apps/v1/namespaces/smoke-smoke-sidecar-1553522890/deployments/vertx-create-span-sidecar,UID:71ccb8b2-4f07-11e9-9b3a-2cbdecb746c7,ResourceVersion:9908,Generation:1,CreationTimestamp:2019-03-25 14:08:20 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{deployment.kubernetes.io/revision: 1,sidecar.jaegertracing.io/inject: agent-as-sidecar,},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:DeploymentSpec{Replicas:*1,Selector:&k8s_io_apimachinery_pkg_apis_meta_v1.LabelSelector{MatchLabels:map[string]string{app: vertx-create-span-sidecar,},MatchExpressions:[],},Template:k8s_io_api_core_v1.PodTemplateSpec{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:,GenerateName:,Namespace:,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: vertx-create-span-sidecar,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,},Spec:PodSpec{Volumes:[],Containers:[{vertx-create-span-sidecar jaegertracing/vertx-create-span:operator-e2e-tests [] []  [{ 0 8080 TCP }] [] [{JAEGER_SERVICE_NAME vertx-create-span-sidecar.smoke-smoke-sidecar-1553522890 nil} {JAEGER_PROPAGATION jaeger,b3 nil}] {map[] map[]} [] [] Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:8080,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:1,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/,Port:8080,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:1,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} nil /dev/termination-log File IfNotPresent nil false false false} {jaeger-agent jaegertracing/jaeger-agent:1.11 [] [--log-level=debug --reporter.grpc.host-port=dns:///agent-as-sidecar-collector-headless.smoke-smoke-sidecar-1553522890:14250 --reporter.type=grpc]  [{zk-compact-trft 0 5775  } {config-rest 0 5778  } {jg-compact-trft 0 6831  } {jg-binary-trft 0 6832  }] [] [] {map[limits.cpu:{{500 -3} {<nil>} 500m DecimalSI} limits.memory:{{134217728 0} {<nil>}  BinarySI}] map[requests.cpu:{{500 -3} {<nil>} 500m DecimalSI} requests.memory:{{134217728 0} {<nil>}  BinarySI}]} [] [] nil nil nil    nil false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[],},ImagePullSecrets:[],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[],HostAliases:[],PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[],RuntimeClassName:nil,EnableServiceLinks:nil,},},Strategy:DeploymentStrategy{Type:RollingUpdate,RollingUpdate:&RollingUpdateDeployment{MaxUnavailable:25%,MaxSurge:25%,},},MinReadySeconds:0,RevisionHistoryLimit:*10,Paused:false,ProgressDeadlineSeconds:*600,},Status:DeploymentStatus{ObservedGeneration:1,Replicas:1,UpdatedReplicas:1,AvailableReplicas:1,UnavailableReplicas:0,Conditions:[{Available True 2019-03-25 14:08:24 +0000 UTC 2019-03-25 14:08:24 +0000 UTC MinimumReplicasAvailable Deployment has minimum availability.} {Progressing True 2019-03-25 14:08:24 +0000 UTC 2019-03-25 14:08:20 +0000 UTC NewReplicaSetAvailable ReplicaSet \"vertx-create-span-sidecar-7d7b9f9b79\" has successfully progressed.}],ReadyReplicas:1,CollisionCount:nil,},}" error="Deployment.apps \"vertx-create-span-sidecar\" is invalid: [spec.template.spec.containers[1].resources.limits[limits.cpu]: Invalid value: \"limits.cpu\": must be a standard resource for containers, spec.template.spec.containers[1].resources.limits[limits.memory]: Invalid value: \"limits.memory\": must be a standard resource for containers, spec.template.spec.containers[1].resources.requests[requests.cpu]: Invalid value: \"requests.cpu\": must be a standard resource for containers, spec.template.spec.containers[1].resources.requests[requests.memory]: Invalid value: \"requests.memory\": must be a standard resource for containers]"
```

This seems interesting:

```
Invalid value: \"limits.cpu\": must be a standard resource for containers, spec.template.spec.containers[1].resources.limits[limits.memory]: Invalid value: \"limits.memory\": must be a standard resource for containers, spec.template.spec.containers[1].resources.requests[requests.cpu]: Invalid value: \"requests.cpu\": must be a standard resource for containers, spec.template.spec.containers[1].resources.requests[requests.memory]: Invalid value: \"requests.memory\": must be a standard resource for containers]"
```

**Comment by pavolloffay** [comment]
@annanay25 any news on this?

**Comment by annanay25** [comment]
Unfortunately I'm unable to get a working minikube setup to debug this further, I will be closing this PR unless someone else is able to pick it up.

**Comment by jpkrohling** [comment]
@annanay25, @objectiser, should we close this one, as something similar has been done with #401?

**Comment by objectiser** [comment]
@jpkrohling yes think so.

**Comment by jpkrohling** [comment]
@annanay25, I'm closing this one, but feel free to reopen if you want to keep working on it.

**Comment by annanay25** [comment]
Sure, thanks @jpkrohling!

Will pick this up as soon as I get time.

**Comment by annanay25** [comment]
@jpkrohling I have cleaned up my branch for this feature, but I don't seem to have permissions to reopen this issue. (I think I should open a clean PR with the changes anyway, do let me know what you'd prefer).

**Pull request closed without merging**
