### PR TITLE
Added Route to SDK Scheme

### LINKED ISSUE #136: error="no kind is registered for the type v1.Route"
The OpenShift-specific feature of creating a Route for the Query deployment seems to be broken after the migration to the SDK 0.1.0:

```
ERRO[0009] failed to create                              error="no kind is registered for the type v1.Route"
ERRO[0009] failed to create                              error="no kind is registered for the type v1.Route" instance="&{{Jaeger io.jaegertracing/v1alpha1} {simplest  default /apis/io.jaegertracing/v1alpha1/namespaces/default/jaegers/simplest 13d08c78-f318-11e8-8426-525400eb2ad2 2518 1 2018-11-28 15:15:37 +0100 CET <nil> <nil> map[] map[] [] nil [] } {allInOne {jaegertracing/all-in-one:1.8 {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} {0  {map[]} {[] [] map[] {map[] map[]}}} { jaegertracing/jaeger-agent:1.8 {map[]} {[] [] map[] {map[] map[]}}} {{[]}} {memory {map[]} {<nil>   }} {<nil> oauth-proxy {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
```

### PR DESCRIPTION
**Pull request by jpkrohling**
Fixes #136 by registering the Route scheme with the SDK Scheme Manager.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/194)

**Comment by jpkrohling** [comment]
The e2e tests for this PR are passing:

```
$ make test
Running unit tests...
?   	github.com/jaegertracing/jaeger-operator/cmd	[no test files]
?   	github.com/jaegertracing/jaeger-operator/cmd/manager	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/account	1.099s	coverage: 100.0% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/apis	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/apis/io/v1alpha1	1.100s	coverage: 16.7% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/cmd/start	[no test files]
?   	github.com/jaegertracing/jaeger-operator/pkg/cmd/version	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/config/sampling	1.099s	coverage: 94.1% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/config/ui	1.100s	coverage: 94.1% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/controller	[no test files]
?   	github.com/jaegertracing/jaeger-operator/pkg/controller/deployment	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/controller/jaeger	3.033s	coverage: 64.3% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/cronjob	1.068s	coverage: 93.5% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/deployment	1.100s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/ingress	0.007s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/inject	0.012s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/route	0.026s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/service	0.027s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/storage	0.010s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/strategy	0.012s	coverage: 99.4% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/util	0.042s	coverage: 100.0% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/version	[no test files]
service/cassandra created
statefulset.apps/cassandra created
statefulset.apps/elasticsearch created
service/elasticsearch created
customresourcedefinition.apiextensions.k8s.io/jaegers.io.jaegertracing created
Formatting code...
Building...
Sending build context to Docker daemon  121.7MB
Step 1/4 : FROM alpine:3.8
 ---> 196d12cf6ab1
Step 2/4 : USER nobody
 ---> Using cache
 ---> 18305c5b670d
Step 3/4 : ADD build/_output/bin/jaeger-operator /usr/local/bin/jaeger-operator
 ---> cc2b448fedb4
Step 4/4 : ENTRYPOINT ["/usr/local/bin/jaeger-operator"]
 ---> Running in ff9a1a4be888
Removing intermediate container ff9a1a4be888
 ---> ab4d9696e6c0
Successfully built ab4d9696e6c0
Successfully tagged jpkroehling/jaeger-operator:latest
Pushing image jpkroehling/jaeger-operator:latest...
Running end-to-end tests...
ok  	github.com/jaegertracing/jaeger-operator/test/e2e	369.321s
```

**Comment by pavolloffay** [comment]
Did you run the e2e on OCP. IIRC they were passing on k8s even without this fix

**Comment by jpkrohling** [comment]
Unfortunately, the E2E tests won't work on OpenShift because some of them depend on the Ingress object. All other tests are passing, though.

**Comment by pavolloffay** [comment]
then they are not almost not relevant  here ;)

**Pull request merged**
