### PR TITLE
Implement backoff limit for jobs

### LINKED ISSUE #1424: Our k8s provider mandates the use of backoffLimit <=3.
How can I set backoffLimit for storage type elasticsearch under esIndexCleaner and dependencies

```
time="2021-04-05T08:05:30Z" level=error msg="failed to apply the changes" error="admission webhook \"xxxxxx.webhook\" denied the request: Job spec in CronJob must set 'backoffLimit' <= 3" execution="2021-04-05 08:05:30.031265563 +0000 UTC" instance=jaeger-tracing-prd namespace=xxxxxxxxx
```

### PR DESCRIPTION
**Pull request by chasekiefer**
Resolves #1424 

## Short description of the changes
- Add optional BackoffLimit to JaegerEsIndexCleanerSpec
- Add optional BackoffLimit to JaegerEsIndexCleanerSpec
- Add optional BackoffLimit to JaegerEsRolloverSpec
- Update es_index_cleaner.go CreateEsIndexCleaner function with BackoffLimit
- Update es_rollover rollover function with BackoffLimit
- Update spark_dependencies.go CreateSparkDependencies function with BackoffLimit
- TestEsIndexCleanerBackoffLimit
- TestEsRolloverBackoffLimit
- Add TestSparkDependenciesBackoffLimit

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
Looks good, but you might need to run `make generate`, the build is failing with:

```
Formatting code...
pkg/cronjob/es_rollover.go
pkg/cronjob/spark_dependencies.go
Build failed: a model has been changed but the generated resources aren't up to date. Run 'make generate' and update your PR.
```

**Review by jpkrohling — APPROVED** [review]
Looks good, just need to figure out the CI failure

**Comment by chasekiefer** [comment]
> Looks good, just need to figure out the CI failure

It looks like it timed out on 02-check-ingress.yaml. Is there anything I can do to help resolve this? Maybe it was just a one-off issue with the e2e test.

**Comment by jpkrohling** [comment]
I'm re-running the jobs, but if this fails again, we'll go forward with the 1.23 release and sort this out later.

**Pull request merged**
