### PR TITLE
Revert metrics in status object

### LINKED ISSUE #307: jaeger-collector and query services are keep on "Rolling update in progress...."
I installed jaeger services via jaeger-operator and ES cluster via template.
Jaeger-collector and query service keep on "Rolling update in progress...." (keep on deleting and creating collector and query pods)

Image: `jaegertracing/jaeger-operator:master`
Image ID: `docker-pullable://docker.io/jaegertracing/jaeger-operator@sha256:448fd68152858a53d7925cc026fa399eb91561f3b618cf1df8c4adb94a386b9e`

OpenShift Master: v3.11.95
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.95

debug log from jaeger operator: 
[jaeger-operator-545c69455d-5v2j8.log](https://github.com/jaegertracing/jaeger-operator/files/2961284/jaeger-operator-545c69455d-5v2j8.log)

Screenshot from 2019-03-13 15-44-21

### PR DESCRIPTION
**Pull request by objectiser**
The reconcile cycle was continuously triggering an update, which wasn't being handled correctly in OCP (according to @jpkrohling kubernetes is better at detecting that deployment hasn't changed, which should be improved in OCP 4, but we need to also support OCP 3.11 for now).

So have reverted the changes from #254, which was causing the update to be applied every 5 seconds. Have also added some more debug logging statements.

We can revisit adding metrics to the Status object at a later date.

Fixes #307 

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/318)

**Comment by objectiser** [comment]
Note: I ran the e2e tests but consistently had failure on daemonset test, which isn't related to this PR:
```
Running Smoke end-to-end tests...
time="2019-03-14T15:13:01Z" level=info msg="passing &{{Jaeger jaegertracing.io/v1} {my-jaeger  smoke-smoke-my-jaeger-1552576371    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[log-level:debug memory.max-traces:10000]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {  {map[]} {[] [] map[] {map[] map[]}}} {{[]}} {{[]}} {  {map[]} {<nil>   } {<nil>     false false false} {<nil> 0  } {   } { {map[] map[]} 0 map[] { <nil>} }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
time="2019-03-14T15:14:12Z" level=info msg="passing &{{Jaeger jaegertracing.io/v1} {agent-as-daemonset  smoke-smoke-daemonset-1552576447    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {allInOne { {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {0 <nil>  {map[]} {[] [] map[] {map[] map[]}}} {DaemonSet  {map[log-level:debug]} {[] [] map[] {map[] map[]}}} {{[]}} {{[]}} {  {map[]} {<nil>   } {<nil>     false false false} {<nil> 0  } {   } { {map[] map[]} 0 map[] { <nil>} }} {<nil>  {[] [] map[] {map[] map[]}}} {[] [] map[] {map[] map[]}}} {}}"
--- FAIL: TestSmoke (256.26s)
    --- FAIL: TestSmoke/smoke (256.24s)
        --- FAIL: TestSmoke/smoke/daemonset (125.46s)
            client.go:57: resource type RoleBinding with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) created
            client.go:57: resource type Role with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) created
            client.go:57: resource type ServiceAccount with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) created
            client.go:57: resource type Deployment with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) created
            utils.go:54: Initialized cluster resources. Namespace: smoke-smoke-daemonset-1552576447
            wait_util.go:67: Deployment available (1/1)
            client.go:57: resource type Jaeger with namespace/name (smoke-smoke-daemonset-1552576447/agent-as-daemonset) created
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            wait_util.go:55: Waiting for full availability of agent-as-daemonset-agent-daemonset daemonsets (0/1)
            daemonset.go:30: timed out waiting for the condition
            client.go:75: resource type Jaeger with namespace/name (smoke-smoke-daemonset-1552576447/agent-as-daemonset) successfully deleted
            client.go:75: resource type Deployment with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) successfully deleted
            client.go:75: resource type ServiceAccount with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) successfully deleted
            client.go:75: resource type Role with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) successfully deleted
            client.go:75: resource type RoleBinding with namespace/name (smoke-smoke-daemonset-1552576447/jaeger-operator) successfully deleted
FAIL
FAIL	github.com/jaegertracing/jaeger-operator/test/e2e	256.325s
```
If one of you could try running the tests to see if you have problems?

cc @kevinearls  - are you also able to do a quick test of this on minishift, using the CR:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegerqe
spec:
  ingress:
    enabled: false
    security: none
  strategy: production
  collector:
    replicas: 1
    image: jaegertracing/jaeger-collector:1.11
    options:
      log-level: debug
      es:
        bulk:
          size: 5000000
          workers: 1
          flush-interval: "200ms"
  query:
    replicas: 1
    image: jaegertracing/jaeger-query:1.11
    options:
      query:
        port: 16686
  agent:
    strategy: sidecar
    image: jaegertracing/jaeger-agent:1.11
  storage:
    type: elasticsearch
    esIndexCleaner:
      enabled: false
    sparkDependencies:
      enabled: false
    options:
      es:
        server-urls: http://elasticsearch:9200
```
(so requires an elasticsearch deployment first).

**Comment by objectiser** [comment]
One more note -this was the logs from one run, even with this change - for some reason the 'desired' number of collectors is thought to be 2 - eventually sorts itself out and returns to 1 - but occasionally see 2 collectors initially being deployed. Looks like a separate issue.
```
time="2019-03-14T14:23:52Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="annotation not present, not injecting" deployment=jaegerqe-collector namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="updating deployment" deployment=jaegerqe-query instance=jaegerqe namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:23:52Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="annotation not present, not injecting" deployment=jaegerqe-collector namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="annotation not present, not injecting" deployment=jaegerqe-collector namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=test
time="2019-03-14T14:23:52Z" level=debug msg="annotation not present, not injecting" deployment=jaegerqe-collector namespace=test
time="2019-03-14T14:23:53Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:23:54Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:23:55Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:23:56Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:23:57Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:23:58Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:23:59Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:00Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:01Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:02Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:03Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:04Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:05Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:06Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:07Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:08Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:09Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:10Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:11Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:12Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:13Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:14Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:15Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:16Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:17Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:18Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=0
time="2019-03-14T14:24:19Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=test
time="2019-03-14T14:24:19Z" level=debug msg="annotation not present, not injecting" deployment=jaegerqe-collector namespace=test
time="2019-03-14T14:24:19Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=1
time="2019-03-14T14:24:20Z" level=debug msg="Waiting for deployment to stabilize" desired=2 name=jaegerqe-collector namespace=test ready=1
time="2019-03-14T14:24:21Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=test
time="2019-03-14T14:24:21Z" level=debug msg="annotation not present, not injecting" deployment=jaegerqe-collector namespace=test
time="2019-03-14T14:24:21Z" level=debug msg="Reconciling Deployment" name=jaegerqe-collector namespace=test
time="2019-03-14T14:24:21Z" level=debug msg="annotation not present, not injecting" deployment=jaegerqe-collector namespace=test
time="2019-03-14T14:24:21Z" level=debug msg="Deployment has stabilized" desired=1 name=jaegerqe-collector namespace=test ready=1
time="2019-03-14T14:24:21Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=test ready=0
time="2019-03-14T14:24:22Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=test ready=0
time="2019-03-14T14:24:23Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=test ready=0
time="2019-03-14T14:24:24Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=test ready=0
time="2019-03-14T14:24:25Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=test ready=0
time="2019-03-14T14:24:26Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=test ready=0
time="2019-03-14T14:24:27Z" level=debug msg="Waiting for deployment to stabilize" desired=1 name=jaegerqe-query namespace=test ready=0
time="2019-03-14T14:24:27Z" level=debug msg="Reconciling Deployment" name=jaegerqe-query namespace=test
time="2019-03-14T14:24:28Z" level=debug msg="Deployment has stabilized" desired=1 name=jaegerqe-query namespace=test ready=1
```

**Comment by objectiser** [comment]
@pavolloffay ok thanks. I'll wait to merge in case Juca or Kevin have any comments - but will merge this evening so ready for @jkandasa to try tomorrow.

**Comment by jpkrohling** [comment]
> which was causing the update to be applied every 5 seconds

If we want a status object, we'll have to update the Jaeger CR after every status update. Each update will then trigger a new event, which might or not be a noop. In case of metrics that change quite often, like what we had before this PR, this new event will detect changes. Which is why we had a 5 seconds pause between reconcile loops. We may want to tweak this pause, or avoid having such metrics as part of the status.

For the first version, I think we should then not have anything in the status object and wait to see what exactly we need to be part of this field.

**Pull request merged**
