### PR TITLE
[e2e] Add e2e test for secrets support

### PR DESCRIPTION
**Pull request by annanay25**

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/167)

**Comment by annanay25** [comment]
Done! @jpkrohling

**Comment by jpkrohling** [comment]
It's still failing for me:

```
$ make test
Running unit tests...
?   	github.com/jaegertracing/jaeger-operator/cmd	[no test files]
?   	github.com/jaegertracing/jaeger-operator/cmd/manager	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/account	0.076s	coverage: 100.0% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/apis	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/apis/io/v1alpha1	0.049s	coverage: 17.0% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/cmd/start	[no test files]
?   	github.com/jaegertracing/jaeger-operator/pkg/cmd/version	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/config/sampling	0.087s	coverage: 94.1% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/config/ui	0.037s	coverage: 94.1% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/controller	[no test files]
?   	github.com/jaegertracing/jaeger-operator/pkg/controller/deployment	[no test files]
ok  	github.com/jaegertracing/jaeger-operator/pkg/controller/jaeger	3.050s	coverage: 64.3% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/cronjob	0.009s	coverage: 93.5% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/deployment	0.022s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/ingress	0.058s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/inject	0.010s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/route	0.017s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/service	0.010s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/storage	0.007s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/strategy	0.008s	coverage: 100.0% of statements
ok  	github.com/jaegertracing/jaeger-operator/pkg/util	0.006s	coverage: 100.0% of statements
?   	github.com/jaegertracing/jaeger-operator/pkg/version	[no test files]
Formatting code...
Building...
Sending build context to Docker daemon  80.48MB
Step 1/4 : FROM alpine:3.8
 ---> 196d12cf6ab1
Step 2/4 : USER nobody
 ---> Using cache
 ---> 18305c5b670d
Step 3/4 : ADD build/_output/bin/jaeger-operator /usr/local/bin/jaeger-operator
 ---> ba65a0df63e4
Step 4/4 : ENTRYPOINT ["/usr/local/bin/jaeger-operator"]
 ---> Running in 41aa90c80081
Removing intermediate container 41aa90c80081
 ---> 7989129cce5d
Successfully built 7989129cce5d
Successfully tagged jpkroehling/jaeger-operator:latest
Pushing image jpkroehling/jaeger-operator:latest...
Running end-to-end tests...
# github.com/jaegertracing/jaeger-operator/test/e2e [github.com/jaegertracing/jaeger-operator/test/e2e.test]
/mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger-operator/test/e2e/secrets.go:47:34: cannot use secret (type "github.com/jaegertracing/jaeger-operator/vendor/k8s.io/api/core/v1".Secret) as type "github.com/jaegertracing/jaeger-operator/vendor/k8s.io/apimachinery/pkg/runtime".Object in argument to f.Client.Create:
	"github.com/jaegertracing/jaeger-operator/vendor/k8s.io/api/core/v1".Secret does not implement "github.com/jaegertracing/jaeger-operator/vendor/k8s.io/apimachinery/pkg/runtime".Object (DeepCopyObject method has pointer receiver)
FAIL	github.com/jaegertracing/jaeger-operator/test/e2e [build failed]
make: *** [Makefile:75: e2e-tests] Error 2
```

**Comment by annanay25** [comment]
My minikube is repeatedly crashing today. Will test on another machine and get back on this soon.

**Comment by jpkrohling** [comment]
Did you manage to get the tests working?

**Comment by annanay25** [comment]
This should work now, @jpkrohling :)

**Comment by jpkrohling** [comment]
@annanay25 were you able to get this working?

**Comment by jpkrohling** [comment]
@kevinearls could you take a look at this PR and see if we have enough coverage in this area already?

**Comment by kevinearls** [comment]
@jpkrohling It would be great add this test, unfortunately it needs to be updated as we've changed all of the tests to use the [stretchr testify framework] (https://github.com/stretchr/testify) for all of our tests.  @annanay25  if you want to update this yourself you could follow this as an example: https://github.com/jaegertracing/jaeger-operator/blob/master/test/e2e/streaming_test.go

If not I could rewrite it myself, it won't take me very long.

**Comment by jpkrohling** [comment]
I'm closing this, as it probably doesn't make sense to bring this up to the newest standards.

**Pull request closed without merging**
