### PR TITLE
Add Jaeger CSV and Package for OLM integration and deployment of the …

### PR DESCRIPTION
**Pull request by awgreene**
…operator through OperatorHub

- This pull requests introduces a CSV and Package which can be bundled together and used by the [Operator Lifecycle Manager](https://github.com/operator-framework/operator-lifecycle-manager) to install, manage, and upgrade the Jaeger Operator in a cluster.

- The Jaeger operator versions available to all Kubernetes clusters using OLM can be updated by submitting a pull request to the [Community Operators GitHub repo](https://github.com/operator-framework/community-operators) that includes the latest CSVs, CRDs, and Packages.

- The CSV was created based of the [documentation provided by OLM](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md) and the [documentation](https://github.com/operator-framework/community-operators/blob/master/docs/marketplace-required-csv-annotations.md) provided by [OperatorHub](https://github.com/operator-framework/operator-marketplace).

- The operator and the CSV were tested using the [scorecard functionality recently introduced](https://github.com/operator-framework/operator-sdk/pull/758) to the [Operator-sdk](https://github.com/operator-framework/operator-sdk). Currently, the Jaeger operator scores a 4/18 on the scorecard tests.

OLM integration could be improved by future code changes to the Operator:
- Addressing the operator-sdk scorecard tests that failed.
- Adding additional information to the Jaeger CSV based on the [CSV documentation provided by OLM](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md)
- Adding additional information to the Jaeger CSV based on the [CSV documentation provided by OperatorHub](https://github.com/operator-framework/community-operators/blob/master/docs/marketplace-required-csv-annotations.md)

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/173)

**Comment by awgreene** [comment]
Hello @jpkrohling, thanks for reviewing my PR.

> What's the source for these keywords? Perhaps distributed could be removed, or perhaps changed to distributed tracing?

I made a best effort attempt at adding the appropriate categories based on the content of the operator - I will follow your suggestion and remove `distributed` from the list of categories.

> Can we reuse this from the role.yaml? Or have a pre-commit hook that checks and blocks the commit if the contents diverge?

Good question - the CSV has to include the service account name and permissions. Creating a pre-commit hook that compares the permissions in the CSV and the openshift role (and vice verse) seems like an appropriate solution. I haven't made a pre-commit hook before, is there an easy way to add a hook that checks that one block of text exists in another?

> I have one more request: could you please add information to the CONTRIBUTING.adoc about how to run the scorecard tests?

I will work on updating the document today.

**Comment by jpkrohling** [comment]
> is there an easy way to add a hook that checks that one block of text exists in another?

It would probably be better to make it as a shell script, so that we can reuse it in the `Makefile` as well, under the `check` target.

If the same YAML is expected in both files, only with different indentation, then the easiest solution would be to play with `tail` and `head` to get the relevant parts from both files, then `sed` to remove any indentation spaces, and finally a `diff` to compare both versions. Does that sound reasonable?

The hook itself is the easy part: just add a `.git/hooks/pre-commit` file (executable) that calls the script mentioned before. AFAIK, hooks aren't part of the repository, so, there could be a new make target that installs the hook.

**Comment by awgreene** [comment]
@jpkrohling I have updated the CONTRIBUTING.adoc to include information about testing the CSV with the operator-sdk. Please let me know if you would like any changes.

**Comment by awgreene** [comment]
@jpkrohling 
>This demonstrates that the contents of this file will get outdated really fast if we don't add some sort of automated check... We are at 1.9 already :-)

The operator-sdk [introduced functionality](https://github.com/operator-framework/operator-sdk/pull/673) on that will generate a CSV based on the deploy files. If the deploy files change and a CSV already exist the sdk will update the changed values in the CSV.

**Comment by awgreene** [comment]
___
*[deploy/olm-catalog/jaeger.package.yaml, line 4 at r3](https://reviewable.io/reviews/jaegertracing/jaeger-operator/173#-LXNng-C9jfiXBEUsOLL:-LXQ8TpK7X8NkpW0aZfL:b-896fix) ([raw file](https://github.com/jaegertracing/jaeger-operator/blob/14952c8bf466a5c806e47eca24476f2894166754/deploy/olm-catalog/jaeger.package.yaml#L4)):*
<details><summary><i>Previously, awgreene (Alexander Greene) wrote…</i></summary><blockquote>

It should be - I failed to update this after upgrading the CSV with the SDK.
</blockquote></details>

Done.

**Comment by awgreene** [comment]
___
*[deploy/olm-catalog/jaeger-operator.csv.yaml, line 16 at r3](https://reviewable.io/reviews/jaegertracing/jaeger-operator/173#-LXNnTyX7vrdyeUruWbi:-LXQ8Sbz7MI3XC2tLjsq:b-896fix) ([raw file](https://github.com/jaegertracing/jaeger-operator/blob/14952c8bf466a5c806e47eca24476f2894166754/deploy/olm-catalog/jaeger-operator.csv.yaml#L16)):*
<details><summary><i>Previously, awgreene (Alexander Greene) wrote…</i></summary><blockquote>

I can make sure to update this now since I have to address the error in the package.
</blockquote></details>

Done.

**Comment by objectiser** [comment]
LGTM

**Pull request merged**
