### PR TITLE
Feat: add `NodeSelector` to jaeger collector, query, and ingestor

### LINKED ISSUE #1351: jaegeroperator to support nodeSelector
On CRD kind Jaeger

```yaml
kind: Jaeger
```

when we enter `nodeSelector:` to some specific components it is not applied. For example:

```yaml
  collector:
    config: {}
    nodeSelector:
      agentpool: service
```

so we request this to be supported so created components (collector/ingester/query) to support nodeSelector.

### PR DESCRIPTION
**Pull request by AhmedGrati**
## Which problem is this PR solving?
- Resolves #1351.
## Short description of the changes
- [x] Update collector, query, and ingester CRD.
- [x] Add unit tests of the previous changes.

### CODE REVIEW

**Review by frzifus — DISMISSED** [review]
Thanks for taking care of it @AhmedGrati!

**Comment by AhmedGrati** [comment]
@frzifus do you have an idea about the issue? it seems that it's irrelevant to the PR.

**Comment by frzifus** [comment]
Not sure, i will try to look into it in the next days.

**Comment by AhmedGrati** [comment]
@frzifus I think it's ready now. As for the `Run miscellaneous E2E tests`, I saw that it's been failing for a while, and we can fix it in another PR if you want.

**Comment by frzifus** [comment]
> As for the Run miscellaneous E2E tests, I saw that it's been failing for a while, and we can fix it in another PR if you want.

I triggered a re-run - fixing the flaky test would be awesome :)

**Review by frzifus — APPROVED** [review]

**Pull request merged**
