### PR TITLE
Add ability to indicate PriorityClass for collector and query

### PR DESCRIPTION
**Pull request by majidazimi**
Note: 

it seems `make generate` introduced some unwanted changes in `deploy/jaegertracing.io_jaegers_crd.yaml`. Not sure whether these changes are required.

### CODE REVIEW

**Comment by jpkrohling** [comment]
>it seems make generate introduced some unwanted changes in deploy/jaegertracing.io_jaegers_crd.yaml. Not sure whether these changes are required.

That does look odd. Looks like we generated it with v0.3.0 of the controller-gen, but we are installing an earlier version: 
https://github.com/jaegertracing/jaeger-operator/blob/d8fbe6c0fdc9d795ea1c6f1316f6882fe86f8e17/Makefile#L396

Could you try removing the controller-gen and installing it using the following command (if you are using Go 1.16 or higher)?

```
go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.4
```

**Review by jpkrohling — APPROVED** [review]
Looks great! Thanks for the contribution!

**Comment by majidazimi** [comment]
So using `controller-gen@v0.3.0` passes all e2e tests.

**Comment by jpkrohling** [comment]
cc @rubenvp8510 , this needs to be added to the changelog for 1.22

**Pull request merged**
