### PR TITLE
Synch changes in cert generation script with CLO

### PR DESCRIPTION
**Pull request by pavolloffay**
Upstream script: https://github.com/openshift/cluster-logging-operator/blob/master/scripts/cert_generation.sh
Full history: https://github.com/openshift/cluster-logging-operator/commits/master/scripts/cert_generation.sh

Ported changes
* https://github.com/openshift/cluster-logging-operator/commit/9793597e5c0706cd31c13d4932c01e9ea363c9a4#diff-5a317832296dcbda4dee718589dca819
* https://github.com/openshift/cluster-logging-operator/commit/d639d0cafbf8ef971c6c9d1455eb60e6cab07ec9#diff-5a317832296dcbda4dee718589dca819
* https://github.com/openshift/cluster-logging-operator/commit/43974cdbc949491cfef8d47e027c48b7087860cd#diff-5a317832296dcbda4dee718589dca819
* https://github.com/openshift/cluster-logging-operator/commit/147393748e23723d834a6a00f3f40e12ddba471f#diff-5a317832296dcbda4dee718589dca819

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay KevinE is running the internal e2e tests, so will wait for those results. But wanted to find out are there going to be any upgrade issues with this? Is there a procedure that will need to be followed - e.g. stop / restart jaeger instance and ES cluster.

**Comment by pavolloffay** [comment]
I would say it should not cause problems. Once new operator is deployed existing certs are reconstructed from secrets and stored on operator's filesystem in `/tmp`. https://github.com/jaegertracing/jaeger-operator/blob/fc993040f2a101c91c0b4b826c0ef8703cb7544a/pkg/storage/elasticsearch_secrets.go#L94

Then the script checks whether certs exist and are not expired https://github.com/jaegertracing/jaeger-operator/blob/b9d6ce77cde4c9d330452ffafd4ad5f9932eb4e2/scripts/cert_generation.sh#L23.

**Comment by objectiser** [comment]
@pavolloffay ok thanks - internal tests passed, so will approve/merge.

**Comment by ewolinetz** [comment]
> Is there a procedure that will need to be followed - e.g. stop / restart jaeger instance and ES cluster.

You will need to restart the ES cluster, but the Elasticsearch Operator handles this for you.
The operator also tries to connect to the ES cluster using a service account token first, so it bypasses any potential issues where the secret has rotated but ES hasn't yet loaded it in.

**Comment by pavolloffay** [comment]
Thanks for looking into this @ewolinetz.

> You will need to restart the ES cluster, but the Elasticsearch Operator handles this for you.

Could you please explain why the ES cluster will have to be restarted? Will the certs change? Could you please point me to the code? 

> The operator also tries to connect to the ES cluster using a service account token first, so it bypasses any potential issues where the secret has rotated but ES hasn't yet loaded it in.

Which operator? Jaeger/jaeger operator is using only certs for auth. If certs change jaeger collector will not able to connect. I am not sure if it restarts automatically. I am going to test this.

**Pull request merged**
