### PR TITLE
Use current namespace for storage

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://github.com/jaegertracing/jaeger-operator/pull/275/files#r263380911

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/278)

**Comment by jpkrohling** [comment]
Could we change the examples to point to ES in the `storage` namespace?

**Comment by pavolloffay** [comment]
I find this more useful for these reasons:

* users might have already running ES cluster in a different namespace
* the current namespace by default is easier to debug

**Comment by pavolloffay** [comment]
Note that storage namespace is configurable in the tests, if you want to force the templates to be in storage namespace we could have simply hardcode that in tests too.

**Comment by pavolloffay** [comment]
@jpkrohling @kevinearls any update?

**Comment by jpkrohling** [comment]
Looks OK to me, but I'll let @kevinearls review as well, as this was introduced by him to fix something specific.

**Pull request merged**
