### PR TITLE
Support custom annotations/labels

### LINKED ISSUE #45: Support custom annotations/labels
We should provide a way for admins to label the resources that are being created. Something like:

```yaml
apiVersion: io.jaegertracing/v1alpha1
kind: Jaeger
metadata:
  name: simple-prod
  labels:
    tenant: acme
spec:
  strategy: all-in-one
  all-in-one:
    annotations:
      prometheus.io/scrape: "false"
```

Note that some labels/annotations might clash with the ones we supply in the operator itself, like the prometheus ones. Because of that, we should always honor what the user specified in the CR.

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes #45 by adding support to custom annotations/labels at the target component level, like:

```yaml
apiVersion: "io.jaegertracing/v1alpha1"
kind: "Jaeger"
metadata:
  name: "labels-and-annotations"
spec:
  all-in-one:
    labels:
      some-label: some-label-value # this is applied to the deployment, pods, services and ingresses
    annotations:
      some-annotation: some-annotation-value # this is *also* applied to the mentioned objects
```

Results in:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    prometheus.io/port: "16686"
    prometheus.io/scrape: "true"
    some-annotation: some-annotation-value
  labels:
    app: jaeger
    jaeger: labels-and-annotations
    some-label: some-label-value
  name: labels-and-annotations
  namespace: default
spec:
  selector:
    matchLabels:
      app: jaeger
      jaeger: labels-and-annotations
  template:
    metadata:
      annotations:
        prometheus.io/port: "16686"
        prometheus.io/scrape: "true"
        some-annotation: some-annotation-value
      labels:
        app: jaeger
        jaeger: labels-and-annotations
        some-label: some-label-value
    spec:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    some-annotation: some-annotation-value
  creationTimestamp: 2018-10-08T09:47:33Z
  generation: 1
  labels:
    some-label: some-label-value
  name: labels-and-annotations-query
---
  kind: Service
  metadata:
    annotations:
      some-annotation: some-annotation-value
    creationTimestamp: 2018-10-08T09:47:33Z
    labels:
      app: jaeger
      jaeger: labels-and-annotations
      some-label: some-label-value
    name: labels-and-annotations-agent
---
  kind: Service
  metadata:
    annotations:
      some-annotation: some-annotation-value
    creationTimestamp: 2018-10-08T09:47:33Z
    labels:
      app: jaeger
      jaeger: labels-and-annotations
      some-label: some-label-value
    name: labels-and-annotations-collector
---
  kind: Service
  metadata:
    annotations:
      some-annotation: some-annotation-value
    creationTimestamp: 2018-10-08T09:47:33Z
    labels:
      app: jaeger
      jaeger: labels-and-annotations
      some-label: some-label-value
    name: labels-and-annotations-query
---
  kind: Service
  metadata:
    annotations:
      some-annotation: some-annotation-value
    creationTimestamp: 2018-10-08T09:47:33Z
    labels:
      app: jaeger
      jaeger: labels-and-annotations
      some-label: some-label-value
    name: labels-and-annotations-zipkin
```

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/50)

**Comment by objectiser** [comment]
Sorry I should have provided some more guidance on #45.

I think one of the main drivers for this feature (at the moment) is to potentially replace the [tracing helm chart ](https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio/charts/tracing)in Istio.

Looking at these values/charts, I believe we need the potential to set labels/annotations on:

* a per deployment basis - so for all-in-one there is only a single deployment, so that could exist under the all-in-one/deployment node - but possibly for production we may need to be able to set labels/annotations individually on the separate deployments

* within a deployment, the labels/annotations for the deployment may be different to those for the template

* a per service basis - this could be independent of the deployment strategy, so could be defined under a service specific node in the CR

* we may also want labels/annotations that can be applied across all three services

* similarly, for the production strategy, we may want some labels/annotations to be common across all three deployments (but specific to the deployment or template?).

So this is looking more complicated, to be able to provide the fine grained configuration of labels/annotations against the various components.

**Comment by jpkrohling** [comment]
Allowing custom labels/annotations to be set for services, but not for deployments (or ingresses, or deployment templates) means that we'd expose this kind of detail about how a "jaeger" instance is composed. What are the concrete use cases you'd be looking to solve with the custom annotations/labels?

**Comment by objectiser** [comment]
Thought it might be best to provide a concrete example from Istio (the Istio 1.0.2 istio-demo.yaml). This file is generated as part of the release build, and is used for demo/test purposes. It is also currently possible for users to specific their own set of annotations that would be used on the jaeger-query service - although not clear what specifically those annotations would be used for.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-tracing
  namespace: istio-system
  labels:
    app: istio-tracing
    chart: tracing-1.0.1
    release: RELEASE-NAME
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
    spec:
      containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.7"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: MEMORY_MAX_TRACES
            value: "50000"
          livenessProbe:
            httpGet:
              path: /
              port: 16686
          readinessProbe:
            httpGet:
              path: /
              port: 16686
          resources:
            requests:
              cpu: 10m
            
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x
```
As you can see, the deployment and template metadata have different sets of labels, and the template has annotations not on the deployment metadata. (BTW Also note the `affinity` node, which is something else we would probably need to deal with - as well as other things like resources, [priority class name and image pull secrets](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/deployment.yaml#L22-L30)).

And services
```
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query
    namespace: istio-system
    annotations:
    labels:
      app: jaeger
      jaeger-infra: jaeger-service
      chart: tracing-1.0.1
      release: RELEASE-NAME
      heritage: Tiller
  spec:
    ports:
      - name: query-http
        port: 16686
        protocol: TCP
        targetPort: 16686
    selector:
      app: jaeger
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    namespace: istio-system
    labels:
      app: jaeger
      jaeger-infra: collector-service
      chart: tracing-1.0.1
      release: RELEASE-NAME
      heritage: Tiller
  spec:
    ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    selector:
      app: jaeger
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent
    namespace: istio-system
    labels:
      app: jaeger
      jaeger-infra: agent-service
      chart: tracing-1.0.1
      release: RELEASE-NAME
      heritage: Tiller
  spec:
    ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    clusterIP: None
    selector:
      app: jaeger
```
The same labels are used across each service apart from the jaeger-infra.

So if we couldn't provide this level of customisation, then we would need to find out from the Istio community whether it was important - otherwise we wouldn't be able to provide the operator as an alternative.

**Comment by jpkrohling** [comment]
I'm closing this one, as I'm not sure this can be reused to solve the requirements.

**Pull request closed without merging**
