### PR TITLE
Publish container - dockerx should not use tag BUILD_IMAGE

### PR DESCRIPTION
**Pull request by morlay**
fix #1267

### CODE REVIEW

**Comment by jpkrohling** [comment]
Under which tag/name is it available with this change?

**Comment by morlay** [comment]
Nope. 

Final image tags passed in `.ci/publish-images.sh`

```
IMAGE_TAGS=${IMAGE_TAGS} make dockerx
```

May refactor in future when all in dockerx

**Comment by jpkrohling** [comment]
> IMAGE_TAGS=${IMAGE_TAGS} make dockerx

The `IMAGE_TAGS` has then to have a default value, like:

```bash
IMAGE_TAGS ?= "--tag $(BUILD_IMAGE)"
```

So that `make dockerx` won't require IMAGE_TAGS when executed locally.

**Comment by morlay** [comment]
Yes, i will upgrade this

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
