### PR TITLE
Removed user_setup script

### LINKED ISSUE #889: Remove add-user script
The container currently creates a user during the startup. While this might be needed in older OpenShift versions, it's not necessary anymore since 4.2. Plain Kubernetes might also not need this, so, we can get rid of this code.

### PR DESCRIPTION
**Pull request by jpkrohling**
Resolves #889 

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
The operator deploys fine with this change in an OCP 4.2 cluster:

```
$ kubectl logs deployment/jaeger-operator -f
time="2020-02-05T12:42:27Z" level=info msg=Versions arch=amd64 identity=observability.jaeger-operator jaeger=1.16.0 jaeger-operator=v1.16.0-25-gf53ad217 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2020-02-05T12:42:31Z" level=info msg="Auto-detected the platform" platform=openshift
time="2020-02-05T12:42:31Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2020-02-05T12:42:31Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2020-02-05T12:42:31Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
```

And minikube:
```
$ minikube start --vm-driver kvm2 --cpus 6 --memory 12288
...
$ kubectl logs deployment/jaeger-operator
time="2020-02-05T12:55:24Z" level=info msg=Versions arch=amd64 identity=observability.jaeger-operator jaeger=1.16.0 jaeger-operator=v1.16.0-25-gf53ad217 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2020-02-05T12:55:25Z" level=info msg="Auto-detected the platform" platform=kubernetes
time="2020-02-05T12:55:25Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=no
time="2020-02-05T12:55:25Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2020-02-05T12:55:25Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2020-02-05T12:55:26Z" level=info msg="Install prometheus-operator in your cluster to create ServiceMonitor objects" error="no ServiceMonitor registered with the API"


```

**Comment by jpkrohling** [comment]
Image for this PR: quay.io/jpkroehling/jaeger-operator:890-Removed-user_setup-script

**Comment by jkandasa** [comment]
@jpkrohling I tested this image on OCP 4.2 cluster via OLM.
I do not see any issues.

Tests performed: 
* Installed jaeger-operator (quay.io/jpkroehling/jaeger-operator:890-Removed-user_setup-script) via OLM
* Deployed Jaeger services with elastic search and performed a minimal test
* Deployed all-in-one service and performed a minimal test


logs from jaeger-operator:
```
time="2020-02-06T15:51:56Z" level=info msg=Versions arch=amd64 identity=openshift-operators.jaeger-operator jaeger=1.16.0 jaeger-operator=v1.16.0-25-gf53ad217 operator-sdk=v0.12.0 os=linux version=go1.13.4
time="2020-02-06T15:52:00Z" level=info msg="Auto-detected the platform" platform=openshift
time="2020-02-06T15:52:00Z" level=info msg="Automatically adjusted the 'es-provision' flag" es-provision=yes
time="2020-02-06T15:52:00Z" level=info msg="Automatically adjusted the 'kafka-provision' flag" kafka-provision=no
time="2020-02-06T15:52:00Z" level=info msg="The service account running this operator does not have the role 'system:auth-delegator', consider granting it for additional capabilities"
time="2020-02-06T15:59:27Z" level=info msg="Storage type not provided. Falling back to 'memory'" instance=jaegerqe namespace=jkandasa
time="2020-02-06T15:59:52Z" level=error msg="failed to store the failed status into the current CustomResource after the reconciliation" error="Operation cannot be fulfilled on jaegers.jaegertracing.io \"jaegerqe\": the object has been modified; please apply your changes to the latest version and try again" execution="2020-02-06 15:59:52.776098605 +0000 UTC" instance=jaegerqe namespace=jkandasa
time="2020-02-06T15:59:52Z" level=error msg="failed to apply the changes" error="routes.route.openshift.io \"jaegerqe\" already exists" execution="2020-02-06 15:59:52.776098605 +0000 UTC" instance=jaegerqe namespace=jkandasa

```

**Comment by jpkrohling** [comment]
Thanks for the confirmation!

**Pull request merged**
