### PR TITLE
Add agent hostNetwork options

### PR DESCRIPTION
**Pull request by chenjinxuan**

### CODE REVIEW

**Comment by chenjinxuan** [comment]
Basic checks has been unable to pass, but I can run it locally

**Comment by jpkrohling** [comment]
@chenjinxuan, apparently, the generated resources need to be updated. This is what I get when I run `make ci` locally:

```
$ make ci
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [kafka:[v1beta1], jaegertracing:[v1], ] 
INFO[0020] Code-generation complete.                    
Formatting code...
pkg/client/versioned/clientset.go
pkg/client/versioned/fake/clientset_generated.go
pkg/client/versioned/fake/register.go
pkg/client/versioned/scheme/register.go
Build failed: a model has been changed but the generated resources aren't up to date. Run 'make generate' and update your PR.
make: *** [Makefile:45: ensure-generate-is-noop] Error 1
```

**Comment by jpkrohling** [comment]
Hey @chenjinxuan , are you still interested in moving forward with this PR?

**Comment by chenjinxuan** [comment]
> Hey @chenjinxuan , are you still interested in moving forward with this PR?

I'm very sorry. In the past period of time, I was very busy and ignored this issue. I will continue to follow up this pr

**Comment by chenjinxuan** [comment]
Sorry, I can't submit this pr

**Comment by jpkrohling** [comment]
That's fine. In any case, thank you for taking some time to play with the code :-) I'm looking forward to your next contribution!

**Pull request closed without merging**
