### PR TITLE
Skip cassandra tests on openshift

### PR DESCRIPTION
**Pull request by kevinearls**
Signed-off-by: Kevin Earls <kearls@redhat.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
What's the reason for this? Are we facing unsolvable problems for Cassandra?

**Comment by kevinearls** [comment]
@jpkrohling I wouldn't say unsolvable, but intermittent problems, and we don't officially support Cassandra on OpenShift anyway.

**Comment by jpkrohling** [comment]
I think we should try to ensure that it works there, even though it's not supported. If you need to temporarily disable it there, I'm fine with it, but disabling it altogether means that we cannot ever tell whether it works in OpenShift at all.

**Comment by jpkrohling** [comment]
I'm merging with the assumption that this will be used only in special situations.

**Pull request merged**
