### PR TITLE
Downgraded to Operator SDK 0.11.0

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@rubenvp8510, @objectiser , could you please review?

**Comment by pavolloffay** [comment]
why? :sob:

**Comment by jpkrohling** [comment]
@pavolloffay not all is lost, this PR is just a plan B. See #809 for more context.

**Comment by rubenvp8510** [comment]
If there is no other option.. this LGTM.

**Comment by jpkrohling** [comment]
@rubenvp8510 is the hero of the day and I'm closing this one in favor of his #814.

**Pull request closed without merging**
