### PR TITLE
Add support for UI configuration

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/115)

**Comment by jpkrohling** [comment]
I'll wait a couple of days to review/merge this one, as I'm currently working on #66, which will have a lot of changes, potentially conflicting with the ones from this PR.

**Comment by objectiser** [comment]
No problem - thanks.

**Comment by jpkrohling** [comment]
The migration to the new operator SDK is now complete. Please, rebase and update this PR.

**Comment by objectiser** [comment]
@jpkrohling Although running the e2e tests, looks like the UI test has failed - so need to investigate, not sure whether something has changed with the UI config format :(

**Comment by objectiser** [comment]
@jpkrohling When running just the new `allInOneWithUIConfigTest` test, I found it was using `jaegertracing/jaeger-operator:1.8.0`. I updated the `operator.yaml` to use the image built/pushed during the `make test`, and it worked fine - so looks like the e2e tests needs to be updated to use the built image.

However when I uncommented all of the other tests, still using the locally built image, it started failing on that new UI test again.

It appears that if `allInOneTest` is uncommented, the problem occurs (i.e. `allInOneTest` and `allInOneWithUIConfigTest` running together). However `allInOneWithUIBasePathTest` and `allInOneWithUIConfigTest` seem to run fine together without `allInOneTest`.

I can't see any reason why the tests would interfere with each other - could you try running the same locally to see if you see the same results?

**Comment by objectiser** [comment]
@jpkrohling I found a workaround - just combining the two UI (base path and config) tests - so if you can't spot anything obvious I will commit this change.

**Pull request merged**
