### PR TITLE
Add owner ref on operator's service to ensure it gets deleted when op…

### PR DESCRIPTION
**Pull request by objectiser**
…erator uninstalled

Signed-off-by: Gary Brown <gary@brownuk.com>

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay I've manually tested this but obvious place to out an automated test, as the e2e tests are run under control of operator sdk which deploys/undeploys the operator. Any suggestions?

**Comment by pavolloffay** [comment]
This seems like a partial solution. The jaeger service is not the only k8s object left if the caller just removes the operator deployment. They should run `k remove -f` on all jaeger operator manifest files they use for installing it. That is the recommended approach to uninstall.

Could we rather set the owner reference in the manifest file? Would it work if we don't know UUID in advance?

> Could possibly add a check in the makefile to see whether the service still remains after the e2e tests have run.

I think we would have to implement a separate test target for this. The e2e tests are run in a separate ns which get cleaned after each run.

**Comment by pavolloffay** [comment]
I see the problem is that this service is created dynamically via the operator. Then this LGTM. We could have defined the service in manifest files.

**Comment by objectiser** [comment]
@pavolloffay Making the service explicit sounded like a good idea, but don't think it is supported by the OLM - it only seems to support deployments.

**Comment by pavolloffay** [comment]
What do you mean by it's not supported by OLM? Do you mean it would not create services defined in manifest files? Is there a pointer to docs?

**Comment by objectiser** [comment]
@pavolloffay Correct. The relevant section of the docs is: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#operator-install

**Pull request merged**
