### PR TITLE
Add install SDK goal to make

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
It should be available in travis output.

**Comment by jpkrohling** [comment]
> It should be available in travis output.

Travis sets the `-x` flag, which prints out more than what it would print locally.

**Comment by pavolloffay** [comment]
The output in travis is the same as locally. What are your concerns with output? Could you be more specific please?


locally:
```
make install-sdk install-tools                                                                                                                    4:39 
curl https://github.com/operator-framework/operator-sdk/releases/download/v0.8.1/operator-sdk-v0.8.1-x86_64-linux-gnu -sLo /home/ploffay/projects/golang/bin/operator-sdk
chmod +x /home/ploffay/projects/golang/bin/operator-sdk
go get -u golang.org/x/lint/golint
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
go get github.com/securego/gosec/cmd/gosec/...
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
```

travis: https://travis-ci.org/jaegertracing/jaeger-operator/jobs/541164268#L230
```
$ make install-sdk install-tools
curl https://github.com/operator-framework/operator-sdk/releases/download/v0.8.1/operator-sdk-v0.8.1-x86_64-linux-gnu -sLo /home/travis/gopath/bin/operator-sdk
chmod +x /home/travis/gopath/bin/operator-sdk
go get -u golang.org/x/lint/golint
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
go get github.com/securego/gosec/cmd/gosec/...
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
```

**Comment by jpkrohling** [comment]
Interesting, I thought Travis was more verbose. My concern is that all our targets are silent, and these new targets are verbose. Instead of showing the commands (curl, chmod, go get...), omit them and their outputs, unless a failure happens.

**Comment by pavolloffay** [comment]
I don't really care this is one-time command folks run when start with the project. 

Do you want to add `@` before the commands?

**Pull request merged**
