### PR TITLE
Allow to pass ES_TIME_RANGE var to Spark dependencies job

### PR DESCRIPTION
**Pull request by Gr1N**
## Which problem is this PR solving?
- https://github.com/jaegertracing/spark-dependencies allows using variable `ES_TIME_RANGE` to specify how far in the past the job should look to for spans. But that variable is missing in the operator. PR simply adds the possibility to pass the required variable.

## Short description of the changes
- added `elasticsearchTimeRange` configuration option for Jaeger dependencies section

### CODE REVIEW

**Comment by Gr1N** [comment]
@jpkrohling @kevinearls review please

**Review by jpkrohling — APPROVED** [review]
LGTM

**Comment by Gr1N** [comment]
@jpkrohling please review again, I've fixed formatting

**Review by jpkrohling — APPROVED** [review]

**Comment by Gr1N** [comment]
@jpkrohling I'm sorry but can you please check PR again? This time I walked through contributing guide and ran everything except e2e tests. Hope everything is ok now.

**Review by jpkrohling — APPROVED** [review]

**Comment by rubenvp8510** [comment]
I don't think the e2e failing is related to the changes made in this PR.

There is an issue with the ingress test, which should be fixed by this PR: https://github.com/jaegertracing/jaeger-operator/pull/1491 As soon as that PR is merged could you rebase?

**Comment by Gr1N** [comment]
@rubenvp8510 yep, no problem

**Comment by jpkrohling** [comment]
PR rebased.

**Comment by Gr1N** [comment]
@jpkrohling thank you for the help and maybe you know when new version of the operator will be available to use?

**Pull request merged**
