### PR TITLE
Update tests to work on OpenShift

### PR DESCRIPTION
**Pull request by kevinearls**
This is the second set of changes for #227.  I've done the following

- Changed several tests to use portForwarding rather than ingress as suggested by @pavolloffay .  This simplifies making them work both on Kubernetes and OpenShift
- Created a version of the daemonsettest called daemonset_with_ingress to cover ingress testing.  This currently does not work on OpenShift as we call WaitForIngress to make sure deplyment has finished, but on OpenShift a route gets created instead.  We need to either figure out how to find routes with kubeclient or start using a openshift client for this test.
- I've refactored a couple of things (specifically creating getVertxDeployment and getJaegerDefinition functions in daemonset test to try to reduce repetition and make test cases shorter.  I'll try to do more of this in the future.

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/323)

**Comment by kevinearls** [comment]
@pavolloffay @objectiser @jpkrohling Please review

**Comment by pavolloffay** [comment]
> We need to either figure out how to find routes with kubeclient or start using a openshift client for this test.

Routes can be queried with the same API as other objects https://github.com/jaegertracing/jaeger-operator/blob/fcb26f488a5960f37fd63221954ac5929c031a9e/pkg/controller/jaeger/route.go#L19

You can use this PR to see how we know that we are running on OCP or k8s https://github.com/jaegertracing/jaeger-operator/pull/217

**Comment by kevinearls** [comment]
HI @objectiser I've updated this based on your previous comments.  Could you please take another look?

**Comment by kevinearls** [comment]
@objectiser I'm looking at that now.  If possible though I'd like to get this merged and add that as a separate issue.

**Comment by objectiser** [comment]
@kevinearls that is fine with me.

**Comment by kevinearls** [comment]
@objectiser Thanks.  Can you merge it then, or do I need review from @pavolloffay and @jpkrohling too?

**Pull request merged**
