### PR TITLE
Bump jaeger version to 1.11

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/300)

**Comment by objectiser** [comment]
@pavolloffay If you agree, let me know and I will create a PR to back out the master change.

**Comment by pavolloffay** [comment]
@objectiser as you want. the release will be soon so it will be overridden anyways no?

**Comment by objectiser** [comment]
@pavolloffay ok will wait for release and then update the readme appropriately.

**Pull request merged**
