### PR TITLE
Add elasticsearch storage date format config.

### PR DESCRIPTION
**Pull request by sniperking1234**
Signed-off-by: Chen Zhengwei <chenzhengwei@inspur.com>

## Which problem is this PR solving?
- Resolves https://github.com/jaegertracing/jaeger/issues/1489
Jaeger can customize the es date format.

## Short description of the changes
- User can configure the date separator to change the date format.
- Default date formate is yyyy-MM-dd, it won't affect the old version.

Depends on: https://github.com/jaegertracing/jaeger/pull/2637 https://github.com/jaegertracing/spark-dependencies/pull/101

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
Sounds reasonable. @kevinearls, given that you are working closer with ES nowadays, could you please review this?

**Comment by jpkrohling** [comment]
@sniperking1234, is this feature available at Jaeger already?

**Comment by kevinearls** [comment]
@jpkrohling this depends on https://github.com/jaegertracing/jaeger/pull/2637 and https://github.com/jaegertracing/spark-dependencies/pull/101

@sniperking1234 After those two are merged I'd like to see an E2E test for this.  You could either add a case to test/e2e/elasticsearch_test.go or modify one of the two test cases that use indices.

**Comment by jpkrohling** [comment]
What's the status of this PR?

**Comment by sniperking1234** [comment]
@jpkrohling The dependent commit is still awaiting review. https://github.com/jaegertracing/spark-dependencies/pull/101

**Review by frzifus — COMMENTED** [review]
We miss `ES_INDEX_DATE_SEPARATOR` in the expected list.
https://github.com/jaegertracing/jaeger-operator/runs/7033393524?check_suite_focus=true#step:6:741

https://github.com/jaegertracing/jaeger-operator/pull/1325/files#diff-e7029db1cb5b0cf6f14e4908db44cac1e36547b7451c0000b062dab700386c7fR83

**Review by kevinearls — APPROVED** [review]
LGTM

**Pull request merged**
