### PR TITLE
add serviceType for the collector service

### PR DESCRIPTION
**Pull request by sschne**
Adds serviceType option for the collector service.

Closes: #1263

Signed-off-by: Simon Schneider <github@simon-schneider.eu>

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
Looks good! Could we have an example under `/examples`, showing how to use it? People ask about this quite often. It would also be good to have this new example as part of the e2e tests, so that we can document whether this works in non-vanilla Kubernetes (OpenShift, for instance).

**Review by jpkrohling — COMMENTED** [review]
LGTM. @kevinearls, would you please check whether the example test looks sane to you?

**Comment by jpkrohling** [comment]
By the way: I just confirmed that the new test is being executed and is passing:

```
2020-11-05T21:29:55.6721753Z     --- PASS: TestExamplesSuite2/TestServiceTypesExample (51.45s)
```

**Review by kevinearls — APPROVED** [review]
The test changes LGTM.

**Review by jpkrohling — APPROVED** [review]

**Comment by sschne** [comment]
Is there anything missing for this PR?

**Comment by jpkrohling** [comment]
No, I was expecting mergify to merge it, but for some reason, it didn't (codecov checks missing?). I merged this manually.

**Pull request merged**
