### PR TITLE
Added grps port into jaeger collector service

### LINKED ISSUE #305: grpc and health check port missing on jaeger collector service
In jaeger-collector service `grpc` and `health-check` ports are missing!

image

### PR DESCRIPTION
**Pull request by jkandasa**
Resolves #305,

Added grpc port into collector service.

### CODE REVIEW

**Comment by jpkrohling** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jaegertracing/jaeger-operator/306)

**Comment by objectiser** [comment]
@pavolloffay I think the grpc port should be exposed, but vaguely remember a discussion about whether the health port should just remain internal, so only accessible by k8s/prometheus?

**Comment by pavolloffay** [comment]
I think healtchecks should be internal

**Comment by objectiser** [comment]
@jkandasa could you update the PR to remove the health check port?

**Comment by jkandasa** [comment]
@objectiser updated.

**Pull request merged**
