### PR TITLE
Issue397

### PR DESCRIPTION
**Pull request by kevinearls**

### CODE REVIEW

**Comment by kevinearls** [comment]
@objectiser @pavolloffay Please review

**Comment by objectiser** [comment]
@kevinearls On the linked issue #397 it says the production_test, elasticsearch_test and es_index_cleaner_test all fail with that issue - however this PR only skips the index cleaner - does this imply the failures in those other tests were because of the index cleaner? In #397, did the index cleaner test run first potentially having a side effect on the others?

**Comment by kevinearls** [comment]
@objectiser Good question.  It's possible it was a side effect.  Since I've refactored the tests into one file if the es_index_cleaner_test fails the other two don't get run.  However, if I skip it the other two pass.

**Comment by objectiser** [comment]
So with the new testify approach the first test failure in a file causes the rest to be skipped? Is there a way to override this when running in ci?

**Comment by kevinearls** [comment]
@objectiser Unfortunately yes, although I don't think this behavior is different from standard Go testing.  In fact, this is not what I expected to see here.  In CI I want all of the tests to run, and this is the behavior I got from Testify when I first tried it with a standalone project.

This may be occurring because we're using the test package from the operator-sdk.  I will continue to investigate and find a way to resolve this.

**Pull request closed without merging**
