### PR TITLE
add cassandraCreateSchema affinity

### LINKED ISSUE #1471: cassandraCreateSchema job not support specify node to schedule
## Requirement - what kind of business use case are you trying to solve?
I hope can set the `affinity` for `cassandraCreateSchema` job just like other jaeger components.

### PR DESCRIPTION
**Pull request by chasekiefer**
Signed-off-by: Chase Kiefer <chase.kiefer@optum.com>

Resolves #1471 

## Short description of the changes
- add affinity to cassandraCreateSchema type
- Modified cassandraDeps for cassandraCreateSchema affinity
- add unit test TestCassandraCreateSchemaAffinity

### CODE REVIEW

**Review by LuChenjing — APPROVED** [review]
Looks great, wish to been merged

**Review by rubenvp8510 — COMMENTED** [review]
LGTM

**Review by rubenvp8510 — APPROVED** [review]

**Comment by jpkrohling** [comment]
This needs to be rebased.

**Comment by jpkrohling** [comment]
End-to-end tests restarted.

**Comment by jpkrohling** [comment]
The tests keep failing: were you able to run them locally? Have you tried this change in a minikube cluster?

**Comment by rubenvp8510** [comment]
I don't think the e2e failing is related to the changes made in this PR.

There is an issue with the ingress test, which should be fixed by this PR: #1491 As soon as that PR is merged could you rebase?

**Comment by chasekiefer** [comment]
@rubenvp8510 Yes, I can. Thank you for pointing this out.

**Comment by jpkrohling** [comment]
That PR was merged and I just rebased this PR.

**Pull request merged**
