### PR TITLE
Do not use resources from common spec in spark dependencies

### PR DESCRIPTION
**Pull request by pavolloffay**
Relates to https://github.com/jaegertracing/jaeger-operator/issues/745#issuecomment-579319297

Using common resources in spark dependencies can be risky because it requires much more memory than other components (collector, query). 

The question is whether we should define default resources for spark (if nothing is defined). The default would be probably 4Gi, which is quite a lot, therefore I would rather do not define anything and depend on good documentation.

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by objectiser** [comment]
Not sure whether this change is required - as currently the problem only occurs if a user sets resource limits at the top level - the implication being it will be inherited by all components unless overridden.

If we start having different rules for different components, it may get confusing.

I agree with your point about good documentation - so maybe instead we should make it clear that if limits are set at the top level it may require specific limits to be set on some components that require more resources, and use spark dependencies as an example?

**Comment by pavolloffay** [comment]
> I agree with your point about good documentation - so maybe instead we should make it clear that if limits are set at the top level it may require specific limits to be set on some components that require more resources, and use spark dependencies as an example?

The problem is that different component has different resource requirements. It just does not make sense to set the common resources to spark job as the spark job requires substantially more memory. The majority of the users will not read the docs and set the limits in the top component which will cause issues as it is causing right now.

I would rather user merging of the common resources only for core components - query, collector, ingester.

**Comment by jpkrohling** [comment]
Do we have a fixed value that is always valid for Spark? Or it is dependent on the workload?

**Comment by pavolloffay** [comment]
It might depend on the workload however. Spark starts at least with 2Gi, the recommendation from the official docs is 8Gi, some unofficial comments in user forums recommend at least 4Gi

**Comment by jpkrohling** [comment]
If it does depend on the workload, then we should be consistent with the other parts of the operator and use the one from the common spec in all components, including spark.

What we could probably do in addition to that is to log a message in the CR's status when we see that the memory is lower than the required value for spark. 

The reasoning for being consistent, even if it means that Spark is broken as a result: as an admin, I would be not pleased if I set a limit to 1Gi and suddenly found that some component is using 8Gi.

**Comment by jpkrohling** [comment]
Sorry, clicked the wrong button and closed the issue...

**Comment by pavolloffay** [comment]
Alright I am closing this, even though I think it shouldn't be like this - given we already have users reporting issues once they set the resources in the common spec.

> The reasoning for being consistent, even if it means that Spark is broken as a result: as an admin, I would be not pleased if I set a limit to 1Gi and suddenly found that some component is using 8Gi.

For instance, we do not merge the common spec for Elasticsaerch resources. It does not make sense because it requires different memory allocations than core jaeger components.

**Comment by jpkrohling** [comment]
> Alright I am closing this, even though I think it shouldn't be like this - given we already have users reporting issues once they set the resources in the common spec.

I think we should really come up with some defaults and document them. It's a bad practice to get pods deployed without limits. Perhaps some of those users would not set the limits in the common spec if we had sensible defaults.

> For instance, we do not merge the common spec for Elasticsaerch resources. It does not make sense because it requires different memory allocations than core jaeger components.

We might want to reconsider this, following with the same reasoning. As an admin, I expect the memory constraints to be applied consistently. I really do not like that we use a value that isn't sufficient for the component, but I like it even less that we are bypassing something that users explicitly set in the CR.

**Pull request closed without merging**
